'use client';
import { useEffect,useState } from 'react';
import { useForm,useWatch } from 'react-hook-form';
import { FileText,Download,BookOpen,CheckCircle2,ShieldCheck,Plus,RefreshCw,MessageSquare } from 'lucide-react';
import { Progress } from '../components/ui/progress';
import { ChartContainer } from '../components/ui/chart';
import { CartesianGrid,Line,LineChart,ReferenceLine,Tooltip,XAxis,YAxis } from 'recharts';
import { emptyRatings,calculate,makeReport,canReview,statusText,round2,rubric,type Assessment,type AssessmentRecord,type Answers,type Model,type Context,type Report,type Rating,type MentorReview,type Priority,type Part } from '../lib/c310-model';
import { istDate,type Identity } from '../lib/jaguar';
import { attributes,weekAt } from '../lib/growth';
import './c310.css';
type Packet={user:Identity;models:Model[];assessments:AssessmentRecord[];contexts:Record<string,Context>;reviewRiders:{email:string;name:string}[]};
type Send=(data:Record<string,unknown>)=>Promise<AssessmentRecord|null>;
const pretty=(d:string)=>new Date(d.length===10?d+'T12:00:00Z':d).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
const fixed=(v:number|null)=>v===null?'Not enough evidence':v.toFixed(2);
const excerpt=(s:string,n=300)=>s.length>n?s.slice(0,n).trimEnd()+'…':s;
function Field({name,children,hint}:{name:string;children:React.ReactNode;hint?:string}){return <label className="c310-field"><span>{name}</span>{children}{hint&&<small>{hint}</small>}</label>;}
function RatingOptions(){return <><option value="">Not enough evidence yet</option>{Array.from({length:11},(_,i)=>i/2).map(n=><option value={n} key={n}>{n.toFixed(n%1?1:0)} / 5</option>)}</>;}
function Criteria({requirements}:{requirements:Report['scores']['gateRequirements']}){return <ul className="c310-criteria">{requirements.map(r=><li key={r.label}><span className={r.met===null?'pending':r.met?'met':'needs'}>{r.met===null?'No decision':r.met?'Met':'Needs attention'}</span><span>{r.label}</span></li>)}</ul>;}
function Curriculum({priority}:{priority:Priority}){return <div className="c310-curriculum"><BookOpen size={17}/><div><strong>Exercises: refer to your C310 curriculum — {priority.code}, Part {priority.part}.</strong><p>Complete the activities assigned by your mentor.</p>{priority.references.length?priority.references.map(c=><div key={c.id}><a href={c.url} target="_blank" rel="noopener noreferrer">{c.title}</a>{c.note&&<small>{c.note}</small>}</div>):<p className="c310-muted">Curriculum activity to be assigned by your mentor.</p>}</div></div>;}
function PriorityCard({p,compact=false}:{p:Priority;compact?:boolean}){return <article className="c310-priority"><div className="c310-priority-head"><span className="c310-code">{p.code} · Part {p.part}</span><span>{round2(p.level)}% factor level · {p.gap.toFixed(2)} points to develop</span></div><h3>{p.name}</h3>{!compact&&<><p>{p.why}</p><p>{p.interpretation}</p></>}<dl><div><dt>{compact?'Keep practising':'What to do'}</dt><dd>{p.do}</dd></div><div><dt>What to avoid</dt><dd>{p.avoid}</dd></div><div><dt>Evidence to keep</dt><dd>{p.proof}</dd></div></dl><p className="c310-source">Source: {p.source.join(' · ')}. Check interpretations with your mentor.</p></article>;}
function AssessmentForm({record,send,busy}:{record:AssessmentRecord;send:Send;busy:boolean}){
 const a=record.assessment,[stage,setStage]=useState(0),form=useForm<Answers>({defaultValues:a.answers}),answers=useWatch({control:form.control}) as Answers,score=calculate(a.model,answers.ratings??a.answers.ratings);
 const {register,handleSubmit,getValues}=form;
 const save=async(values:Answers,generate=false)=>{const saved=await send({op:'draft',id:a.id,revision:record.revision,answers:values});if(saved&&generate)await send({op:'submit',id:a.id,revision:saved.revision});};
 return <form className="c310-assessment" onSubmit={handleSubmit(v=>save(v))}><div className="c310-title-row"><div><span className="overline">SAVED DRAFT · {a.model.version}</span><h2>Your assessment</h2><p>Rate observed behaviour. Choose “Not enough evidence yet” when you cannot judge a part.</p></div><span className="c310-status">{score.factors.filter(f=>f.blended!==null).length}/10 factors complete</span></div><div className="c310-form-grid"><Field name="Chosen subject / application"><input maxLength={160} placeholder="For example, Oracle Fusion HCM" {...register('subject')}/></Field><Field name="Chosen route / path"><input maxLength={160} placeholder="Functional, technical, both or your chosen route" {...register('path')}/></Field><Field name="Assessment date"><input type="date" max={istDate()} {...register('date')}/></Field><Field name="Scoring-model version"><output>{a.model.version}</output></Field></div><div className="c310-stage-tabs" aria-label="Assessment stages">{['C1 · Confidence','C2 · Cognition','C3 · Consistency','Review answers'].map((s,i)=><button type="button" key={s} aria-pressed={stage===i} onClick={()=>setStage(i)}>{s}</button>)}</div>
 {stage<3?<><div className="c310-rubric"><details><summary>How to use the 0–5 rubric</summary><div>{rubric.map(([n,s])=><p key={n}><b>{n}</b> · {s}</p>)}<p>Half marks are allowed between adjacent levels. Communication is judged by usefulness, not accent, stammering or style. Confidence and consistency need context and examples over time.</p></div></details></div>{a.model.factors.map((f,i)=>f.code.startsWith(`C${stage+1}`)?<section className="c310-factor card" key={f.code}><div className="c310-factor-head"><div><span className="c310-code">{f.code} · {f.weight} weighted points</span><h3>{f.name}</h3></div>{f.provisional&&<span className="c310-working">Provisional {f.p1Share*100}/{f.p2Share*100} split</span>}</div><div className="c310-parts">{([1,2] as const).map(part=><div key={part}><span className="overline">PART {part} · {Math.round((part===1?f.p1Share:f.p2Share)*100)}%</span><p>{part===1?f.p1:f.p2}</p><Field name={`${f.code} Part ${part} rating`}><select {...register(`ratings.${i}.${part===1?'p1':'p2'}`,{setValueAs:v=>v===''?null:Number(v)})}><RatingOptions/></select></Field><Field name="Evidence / short example (optional)"><textarea maxLength={800} placeholder="What happened? What did you do? What changed?" {...register(`ratings.${i}.${part===1?'e1':'e2'}`)}/></Field></div>)}</div></section>:null)}<div className="c310-form-grid"><Field name="Structural barriers (separate from the rating)"><textarea maxLength={2400} placeholder="Access, cost, caring commitments, exclusion or other constraints" {...register('barriers')}/></Field><Field name="Support or accommodations needed"><textarea maxLength={2400} {...register('support')}/></Field></div></>:<section className="card"><h3>Check before generating</h3><div className="c310-scroll"><table><thead><tr><th>Factor</th><th>Part 1</th><th>Part 2</th><th>Blended / 5</th></tr></thead><tbody>{score.factors.map(f=><tr key={f.code}><th>{f.code} · {f.name}</th><td>{f.p1??'Not enough evidence'}</td><td>{f.p2??'Not enough evidence'}</td><td>{fixed(f.blended)}</td></tr>)}</tbody></table></div><p>{score.complete?`Score-B ${score.scoreB!.toFixed(2)}; Score-A ${score.scoreA!.toFixed(2)}. These are self-ratings; mentor confirmation is pending.`:'Incomplete assessment: no final score or gate decision. Save it and return when you have enough evidence.'}</p><Field name="Your reflection or questions for the mentor"><textarea maxLength={2400} {...register('reflection')}/></Field><p className="c310-muted">Generating preserves this dated assessment. Later changes become a new assessment. High self-ratings are a starting point for review, not proof of complete mastery.</p></section>}
 <div className="c310-actions"><span className="c310-muted">Saved {pretty(record.updatedAt)} · {a.status}</span><button type="submit" disabled={busy}>{busy?'Saving…':'Save draft'}</button>{stage<3?<button type="button" className="primary" onClick={()=>setStage(stage+1)}>Next stage</button>:<button type="button" className="primary" disabled={busy||!score.complete||!answers.subject||!answers.path} onClick={handleSubmit(v=>save(v,true))}>Save & generate report</button>}</div></form>;
}
function Scenario({report,onChange}:{report:Report;onChange:(v:Rating[]|null)=>void}){
 const basis=report.mentorRatings??report.selfRatings,[ratings,setRatings]=useState(()=>structuredClone(basis)),[open,setOpen]=useState(false),s=calculate(report.model,ratings,report.outcome);const changed=ratings.some((r,i)=>r.p1!==basis[i].p1||r.p2!==basis[i].p2);
 const patch=(i:number,part:Part,v:string)=>{const next=ratings.map((r,n)=>n===i?{...r,[part===1?'p1':'p2']:v===''?null:Number(v)}:r);setRatings(next);onChange(next);};
 return <section className="c310-scenario"><button type="button" aria-expanded={open} onClick={()=>setOpen(!open)}>What would improvement look like?</button>{open&&<><p>This is hypothetical. It does not change the assessment, project outcome or certification decision.</p><div className="c310-scroll"><table><thead><tr><th>Factor</th><th>Proposed Part 1</th><th>Proposed Part 2</th></tr></thead><tbody>{ratings.map((r,i)=><tr key={r.code}><th>{r.code}</th>{([1,2] as const).map(p=><td key={p}><select aria-label={`Hypothetical ${r.code} Part ${p}`} value={r[p===1?'p1':'p2']??''} onChange={e=>patch(i,p,e.target.value)}><RatingOptions/></select></td>)}</tr>)}</tbody></table></div><div className="c310-hypo-result"><strong>Hypothetical Score-B {fixed(s.scoreB)}</strong><span>Score-A {fixed(s.scoreA)} · real Score-B {fixed(report.scores.scoreB)}</span></div><p>Certification has specific minimums and an authorised project pass. A 90+ score is an aspiration, not an additional certification requirement.</p><button type="button" onClick={()=>{setRatings(structuredClone(basis));onChange(null);}}>Reset hypothetical changes</button>{changed&&<p className="c310-muted">The PDF download can include these clearly labelled hypothetical changes.</p>}</>}</section>;
}
function ReportView({report,liveReview}:{report:Report;liveReview:MentorReview|null}){
 const [page,setPage]=useState(1),[scenario,setScenario]=useState<Rating[]|null>(null);const all=[...report.priorities,...report.supporting,...report.strengths];const pdf=`/api/c310/${report.assessmentId}/pdf?report=${encodeURIComponent(report.id)}${scenario?'&scenario='+encodeURIComponent(JSON.stringify(scenario.map(r=>({code:r.code,p1:r.p1,p2:r.p2})))):''}`;
 const mentor=report.mentorRatings;void liveReview;
 return <div className="c310-report"><div className="c310-title-row"><div><span className="overline">EMPLOYABLE SKILL MATRIX · {report.source.toUpperCase()}</span><h2>{report.riderName}’s development report</h2><p>{report.answers.subject} · {report.answers.path} · {pretty(report.answers.date)} · {report.model.version}</p></div><a className="primary" href={pdf}><Download size={17}/>Download four-page PDF</a></div><nav className="c310-page-tabs" aria-label="Report pages">{['Your score','Priorities','Strengths & curriculum','Evidence & rescore'].map((s,i)=><button key={s} aria-current={page===i+1?'page':undefined} onClick={()=>setPage(i+1)}><span>{i+1}</span>{s}</button>)}</nav>
 <article className="c310-paper"><span className="c310-page-label">PAGE {page} OF 4</span>
 {page===1&&<><h2>Your score. Your next move.</h2><div className="c310-score-row"><div className="main"><span>Score-B · overall development</span><strong>{fixed(report.scores.scoreB)}<small>/100</small></strong></div><div><span>Score-A · Ownership entry</span><strong>{fixed(report.scores.scoreA)}<small>/100</small></strong></div><div><span>Ownership project</span><strong className="word">{report.outcome?.project??'Not assessed'}</strong></div></div><p className="c310-status-banner">{statusText(report)}</p><p className="c310-summary">{report.summary}</p><p className="c310-muted">Score-B totals all weighted points. Score-A excludes C1B and uses {report.scores.denominatorA} available weighted points. A score is a development snapshot, not a measure of your worth or a salary prediction.</p><div className="c310-scroll"><table className="c310-factor-table"><thead><tr><th>Factor</th><th>Level / 100%</th><th>Weighted points</th></tr></thead><tbody>{report.scores.factors.map(f=><tr key={f.code}><th><b>{f.code}</b> {f.name}{f.provisional&&<small>Provisional {f.p1Share*100}/{f.p2Share*100} split</small>}</th><td><span>{f.level===null?'Not assessed':round2(f.level)+'%'}</span><Progress value={f.level??0} aria-label={`${f.code} factor level ${f.level===null?'not assessed':round2(f.level)+' percent'}`}/></td><td>{fixed(f.points)} / {f.weight}</td></tr>)}</tbody></table></div><div className="c310-two"><section><h3>Ownership-entry requirements</h3><Criteria requirements={report.scores.gateRequirements}/></section><section><h3>Certification requirements</h3><Criteria requirements={report.scores.certRequirements}/></section></div><p className="c310-muted">{report.source==='Self-rated'?'Threshold checks are based on your self-ratings; only an authorised reviewer can confirm project and certification outcomes.':`Independent mentor ratings confirmed by ${report.reviewer} on ${report.reviewDate?pretty(report.reviewDate):pretty(report.generatedAt)}.`}</p></>}
 {page===2&&<><h2>Your development priorities</h2><p>Mandatory minimums and certification blockers come first. Other priorities consider factor levels and weighted point gaps.</p><div className="c310-priority-grid">{report.priorities.map(p=><PriorityCard key={p.code} p={p}/>)}</div><p className="c310-muted">Part 1 / Part 2 gaps suggest questions to investigate. They are not established personality facts. One mistake does not automatically reduce a rating.</p></>}
 {page===3&&<><h2>Keep the strengths. Shift the habits.</h2>{report.strengths.length>0&&<><h3>Maintain the stronger rated areas</h3><div className="c310-priority-grid">{report.strengths.map(p=><PriorityCard compact key={p.code} p={p}/>)}</div><p className="c310-muted">High ratings need repeated, varied evidence. They are not proof that development is finished.</p></>}{report.supporting.length>0&&<><h3>Supporting development</h3><div className="c310-priority-grid">{report.supporting.map(p=><PriorityCard compact key={p.code} p={p}/>)}</div></>}<h3>Exercises / Go to your curriculum</h3>{all.map(p=><Curriculum priority={p} key={p.code}/>)}{report.model.note&&<p className="c310-working-note">{report.model.note}</p>}</>}
 {page===4&&<><h2>Build evidence. Then rescore.</h2><ol className="c310-cycle">{report.reviewCycle.map(c=><li key={c.week}><strong>{c.week}</strong><p>{c.action}</p></li>)}</ol><h3>Compare ratings, then check the examples</h3><div className="c310-scroll"><table><thead><tr><th>Factor</th><th>Self P1 / P2</th><th>Mentor P1 / P2 at snapshot</th></tr></thead><tbody>{report.selfRatings.map(r=>{const m=mentor?.find(m=>m.code===r.code);return <tr key={r.code}><th>{r.code}</th><td>{r.p1??'—'} / {r.p2??'—'}</td><td>{m?.p1??'Not reviewed'} / {m?.p2??'Not reviewed'}</td></tr>;})}</tbody></table></div>{report.mentorComments&&<p className="c310-status-banner">Mentor observation: {excerpt(report.mentorComments,180)}</p>}<div className="c310-two"><section><h3>Barriers and support</h3><p>{excerpt(report.answers.barriers)||'No structural barriers recorded.'}</p><p>{excerpt(report.answers.support)||'Discuss useful support and accommodations with your mentor.'}</p></section><section><h3>Recorded game/work evidence</h3>{report.context.work.length?report.context.work.slice(-3).map(w=><div className="c310-work" key={w.id}><strong>{w.attribute||'Work observation'} · {pretty(w.date)}</strong><p>{excerpt(w.observation,180)}</p><p>{excerpt(w.evidence,180)}</p></div>):<p>No reviewed game/work evidence was linked when this snapshot was generated.</p>}</section></div><section className="c310-weekly"><h3>Your river practice plan</h3><p>Weakest eight → C1-first weekly three → lowest selected grade for weekend practice.</p><p><b>Assessment suggestions:</b> {report.weekend.targets.join(' · ')}. Weekend: {report.weekend.weekend||'Not available'}.</p>{report.context.weekly.length?report.context.weekly.slice(-2).map(w=><p key={w.week}><b>Agreed week {w.week}:</b> {w.targets.join(' · ')} · weekend {w.weekend} · {w.status}. Source: {w.basis}.</p>):<p>Ask your mentor to agree and carry priorities into the weekend plan.</p>}<p className="c310-muted">Existing saved priorities remain in place. Assessment suggestions use blended factor grades and become a plan only after mentor agreement.</p></section><Scenario key={report.id} report={report} onChange={setScenario}/><p className="c310-muted">Review useful and difficult examples; compare ratings with observable evidence. This is a provisional development model, not a clinical diagnosis.</p></>}
 </article></div>;
}
function MentorForm({record,user,send,busy}:{record:AssessmentRecord;user:Identity;send:Send;busy:boolean}){
 const a=record.assessment,draft=[...a.mentorReviews].reverse().find(r=>r.mentor===user.email&&r.status==='Draft'),form=useForm({defaultValues:{ratings:structuredClone(draft?.ratings??emptyRatings()),date:draft?.date??istDate(),comment:draft?.comment??'',factorComments:draft?.factorComments??{} as Record<string,string>}}),values=useWatch({control:form.control}),scores=calculate(a.model,(values.ratings??emptyRatings()) as Rating[]);
 const save=async(confirm=false)=>{const saved=await send({op:'mentor_draft',id:a.id,revision:record.revision,reviewId:draft?.id??null,...form.getValues()});if(saved&&confirm){const review=[...saved.assessment.mentorReviews].reverse().find(r=>r.mentor===user.email&&r.status==='Draft');if(review)await send({op:'mentor_confirm',id:a.id,revision:saved.revision,reviewId:review.id});}};
 return <form className="card c310-mentor-form" onSubmit={form.handleSubmit(()=>save())}><div className="c310-title-row"><div><span className="overline">INDEPENDENT MENTOR RATINGS</span><h3>Review {a.riderName}</h3><p>Your ratings are stored separately from the rider’s self-ratings.</p></div><span className="c310-status">{scores.complete?'All parts assessed':'Draft · incomplete'}</span></div><Field name="Mentor observation date"><input type="date" max={istDate()} {...form.register('date')}/></Field>{a.model.factors.map((f,i)=>{const self=a.answers.ratings.find(r=>r.code===f.code)!;return <details className="c310-mentor-factor" key={f.code}><summary>{f.code} · {f.name}<span>Self {self.p1??'—'} / {self.p2??'—'}</span></summary><div className="c310-parts">{([1,2] as const).map(part=><div key={part}><strong>Part {part}</strong><p>{part===1?f.p1:f.p2}</p><p className="c310-evidence"><b>Rider example:</b> {self[part===1?'e1':'e2']||'No example supplied.'}</p><Field name={`Mentor ${f.code} Part ${part} rating`}><select {...form.register(`ratings.${i}.${part===1?'p1':'p2'}`,{setValueAs:v=>v===''?null:Number(v)})}><RatingOptions/></select></Field><Field name="Mentor evidence (optional)"><textarea maxLength={800} {...form.register(`ratings.${i}.${part===1?'e1':'e2'}`)}/></Field></div>)}</div><Field name={`${f.code} feedback / observation`}><textarea maxLength={2400} {...form.register(`factorComments.${f.code}`)}/></Field></details>;})}<Field name="Review summary, evidence and agreed priorities"><textarea maxLength={2400} {...form.register('comment')}/></Field><p className="c310-muted">Preview: mentor Score-B {fixed(scores.scoreB)} · Score-A {fixed(scores.scoreA)}. No confirmed decision is recorded until you confirm this review.</p><div className="c310-actions"><button disabled={busy} type="submit">Save mentor draft</button><button className="primary" type="button" disabled={busy||!scores.complete||!values.comment} onClick={()=>save(true)}>Confirm independent review</button></div></form>;
}
function CurriculumForm({record,send,busy}:{record:AssessmentRecord;send:Send;busy:boolean}){
 const [code,setCode]=useState('C1A'),[part,setPart]=useState<Part>(1),[title,setTitle]=useState(''),[url,setUrl]=useState(''),[note,setNote]=useState('');
 return <form className="card" onSubmit={e=>{e.preventDefault();void send({op:'assign',id:record.assessment.id,revision:record.revision,code,part,title,url,note});}}><h3>Assign an actual curriculum activity</h3><p>Use an existing activity title and link. Leave missing mappings to be assigned; do not invent exercises.</p><div className="c310-form-grid"><Field name="Factor"><select value={code} onChange={e=>setCode(e.target.value)}>{attributes.map(([c,n])=><option value={c} key={c}>{c} · {n}</option>)}</select></Field><Field name="Part"><select value={part} onChange={e=>setPart(Number(e.target.value) as Part)}><option value={1}>Part 1</option><option value={2}>Part 2</option></select></Field><Field name="Existing activity title"><input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field name="Actual activity URL"><input type="url" required maxLength={2048} placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/></Field></div><Field name="Assignment note"><textarea maxLength={2400} value={note} onChange={e=>setNote(e.target.value)}/></Field><div className="c310-actions"><button className="primary" disabled={busy}>Assign curriculum activity</button></div></form>;
}
function OutcomeForm({record,send,busy}:{record:AssessmentRecord;send:Send;busy:boolean}){
 const a=record.assessment,previous=a.outcomes.at(-1),[project,setProject]=useState(previous?.project??'Not assessed'),[evidence,setEvidence]=useState(previous?.evidence??''),[certified,setCertified]=useState(previous?.certified??false),mentor=[...a.mentorReviews].reverse().find(r=>r.status==='Confirmed'),scores=mentor?calculate(a.model,mentor.ratings,{id:'preview',project,evidence,certified:false,by:'',date:''}):null;
 return <form className="card" onSubmit={e=>{e.preventDefault();void send({op:'outcome',id:a.id,revision:record.revision,project,evidence,certified});}}><span className="overline">LAVY · AUTHORISED OUTCOMES</span><h3>Ownership project and certification</h3><Field name="Ownership project status"><select value={project} onChange={e=>setProject(e.target.value as typeof project)}><option>Not assessed</option><option disabled={!scores?.gate}>Passed</option><option>Needs further work</option></select></Field><Field name="Project evidence and decision reason"><textarea maxLength={2400} value={evidence} onChange={e=>setEvidence(e.target.value)}/></Field><label className="c310-check"><input type="checkbox" checked={certified} disabled={!scores?.cert} onChange={e=>setCertified(e.target.checked)}/>Confirm certification after all requirements and the project pass are verified</label><p className="c310-muted">{scores?.cert?'Confirmed mentor ratings and the selected project outcome meet the thresholds.':'Certification remains pending until every requirement is satisfied.'}</p><div className="c310-actions"><button className="primary" disabled={busy}>Record authorised outcome</button></div></form>;
}
function WeekendForm({record,send,busy,ctx}:{record:AssessmentRecord;send:Send;busy:boolean;ctx:Context}){
 const [week,setWeek]=useState(Math.max(1,Math.min(14,weekAt(ctx.riverStart??'2026-10-03',istDate()))));const report=[...record.assessment.reports].reverse().find(r=>r.source==='Mentor-rated');
 return <section className="card"><h3>Agree the river weekend plan</h3><p>Keep any existing selected priorities. If no tracker assessment is available, use this confirmed report’s blended grades with the same weakest-eight/C1-first selection rule.</p>{report&&<p><b>Assessment suggestion:</b> {report.weekend.targets.join(' · ')} · lowest selected: {report.weekend.weekend}</p>}{ctx.weekly.slice(-2).map(w=><p key={w.week}><b>Existing week {w.week}:</b> {w.targets.join(' · ')} · weekend {w.weekend} · {w.status}</p>)}<Field name="River week"><input type="number" min="1" max={ctx.riverWeeks??14} value={week} onChange={e=>setWeek(Number(e.target.value))}/></Field><button className="primary" disabled={busy||!report} onClick={()=>send({op:'weekend',id:record.assessment.id,revision:record.revision,week})}>Agree & add to weekend plan</button><p className="c310-muted">A reviewed game mistake supplies evidence for discussion; it does not automatically change a score.</p></section>;
}
function ModelEditor({model,publish,busy}:{model:Model;publish:(data:unknown)=>void;busy:boolean}){
 const [d,setD]=useState(()=>structuredClone(model));
 return <form className="card" onSubmit={e=>{e.preventDefault();const {id:ignored,createdAt:ignored2,...data}=d;void ignored;void ignored2;publish(data);}}><h2>Publish a new model version</h2><p>Existing assessments retain their own model snapshot. Publishing never recalculates historical results.</p><Field name="New version label"><input required maxLength={160} value={d.version} onChange={e=>setD({...d,version:e.target.value})}/></Field><div className="c310-scroll"><table><thead><tr><th>Factor</th><th>Weight</th><th>Part 1 %</th><th>Part 2 %</th><th>Working setting</th></tr></thead><tbody>{d.factors.map((f,i)=><tr key={f.code}><th>{f.code} · {f.name}</th><td><input aria-label={`${f.code} weight`} type="number" min="0.1" max="100" step="0.1" value={f.weight} onChange={e=>setD({...d,factors:d.factors.map((x,n)=>n===i?{...x,weight:Number(e.target.value)}:x)})}/></td><td><input aria-label={`${f.code} Part 1 share percent`} type="number" min="0" max="100" step="1" value={round2(f.p1Share*100)} onChange={e=>{const share=Number(e.target.value)/100;setD({...d,factors:d.factors.map((x,n)=>n===i?{...x,p1Share:share,p2Share:1-share}:x)});}}/></td><td>{round2(f.p2Share*100)}%</td><td><label className="c310-check"><input type="checkbox" checked={f.provisional} onChange={e=>setD({...d,factors:d.factors.map((x,n)=>n===i?{...x,provisional:e.target.checked}:x)})}/>Provisional</label></td></tr>)}</tbody></table></div><div className="c310-form-grid">{Object.entries(d.gate).map(([key,value])=><Field key={key} name={{scoreA:'Ownership Score-A minimum',c1aP1:'C1A Part 1 minimum',c1cP1:'C1C Part 1 minimum',c1cP2:'C1C Part 2 minimum',c2bP2:'C2B Part 2 minimum'}[key]??key}><input type="number" min="0" max={key==='scoreA'?100:5} step="0.5" value={value} onChange={e=>setD({...d,gate:{...d.gate,[key]:Number(e.target.value)}})}/></Field>)}<Field name="Certification C1B level minimum %"><input type="number" min="0" max="100" value={d.cert.c1bLevel} onChange={e=>setD({...d,cert:{...d.cert,c1bLevel:Number(e.target.value)}})}/></Field><Field name="Certification Score-B minimum"><input type="number" min="0" max="100" value={d.cert.scoreB} onChange={e=>setD({...d,cert:{...d.cert,scoreB:Number(e.target.value)}})}/></Field></div><Field name="Working-model note / change explanation"><textarea maxLength={2400} value={d.note} onChange={e=>setD({...d,note:e.target.value})}/></Field><div className="c310-actions"><span>Total weight: {round2(d.factors.reduce((n,f)=>n+f.weight,0))} / 100</span><button className="primary" disabled={busy}>Publish new immutable version</button></div></form>;
}
function HistoryChart({records}:{records:AssessmentRecord[]}){
 const data=[...records].filter(r=>r.assessment.reports.length).reverse().map(r=>{const a=r.assessment,self=[...a.reports].reverse().find(r=>r.source==='Self-rated'),mentor=[...a.reports].reverse().find(r=>r.source==='Mentor-rated');return {date:a.answers.date,self:self?.scores.scoreB??null,mentor:mentor?.scores.scoreB??null};});
 if(data.length<2)return null;
 return <section className="card"><h3>Your development across assessments</h3><ChartContainer className="c310-history-chart" config={{self:{label:'Self Score-B',color:'#6555a4'},mentor:{label:'Mentor Score-B',color:'#0f6c72'}}} aria-label="Score-B history from self and mentor assessments, zero to one hundred"><LineChart accessibilityLayer data={data} margin={{top:12,left:0,right:20,bottom:5}}><CartesianGrid vertical={false}/><XAxis dataKey="date" tickFormatter={d=>pretty(d).replace(/ 20\d\d$/,'')}/><YAxis domain={[0,100]} ticks={[0,20,40,60,80,100]}/><Tooltip/><ReferenceLine y={70} stroke="#7e8996" strokeDasharray="4 4"/><Line type="linear" dataKey="self" name="Self Score-B" stroke="#6555a4" strokeWidth={2.5} connectNulls={false} isAnimationActive={false}/><Line type="linear" dataKey="mentor" name="Mentor Score-B" stroke="#0f6c72" strokeWidth={2.5} connectNulls={false} isAnimationActive={false}/></LineChart></ChartContainer><div className="c310-chart-legend"><span>Self-rated Score-B</span><span>Mentor-rated Score-B</span><span>70 line: overall minimum, with other requirements still required</span></div><details><summary>Exact history values</summary><div className="c310-scroll"><table><thead><tr><th>Assessment date</th><th>Self Score-B</th><th>Mentor Score-B</th></tr></thead><tbody>{data.map((d,i)=><tr key={i}><th>{pretty(d.date)}</th><td>{fixed(d.self)}</td><td>{fixed(d.mentor)}</td></tr>)}</tbody></table></div></details></section>;
}
const emptyContext:Context={work:[],weekly:[],curriculum:[]};
export default function MyC310({user}:{user:Identity}){
 const [packet,setPacket]=useState<Packet|null>(null),[selected,setSelected]=useState(''),[snapshot,setSnapshot]=useState(''),[section,setSection]=useState<'mine'|'mentor'|'models'>('mine'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('');
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/c310',{cache:'no-store'}),b=await r.json() as Packet&{error?:string};if(!r.ok)throw new Error(b.error??'Could not load C310 reports.');setPacket(b);}catch(e){setError(e instanceof Error?e.message:'C310 reports are unavailable.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[user.email]);
 const send:Send=async data=>{setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/c310',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),b=await r.json() as {record?:AssessmentRecord;context?:Context;model?:Model;message?:string;error?:string};if(!r.ok)throw new Error(b.error??'Could not save. Your open draft has been kept.');if(b.record){const rec=b.record;setPacket(old=>old?{...old,assessments:[rec,...old.assessments.filter(r=>r.assessment.id!==rec.assessment.id)],contexts:{...old.contexts,[rec.assessment.id]:b.context??emptyContext}}:old);setSelected(rec.assessment.id);setSnapshot('');setSuccess(b.message??'Saved. Your earlier reports remain in history.');return rec;}if(b.model){const model=b.model;setPacket(old=>old?{...old,models:[model,...old.models]}:old);setSuccess('New model version saved. Historical assessments are unchanged.');}return null;}catch(e){setError(e instanceof Error?e.message:'Could not save. Your open draft has been kept.');return null;}finally{setBusy(false);}};
 const mine=packet?.assessments.filter(r=>r.assessment.rider===user.email)??[],mentees=packet?.assessments.filter(r=>canReview(user,r.assessment.rider))??[],visible=section==='mentor'?mentees:mine,record=visible.find(r=>r.assessment.id===selected),a=record?.assessment,ctx=a?packet?.contexts[a.id]??emptyContext:emptyContext,report=a?(a.reports.find(r=>r.id===snapshot)??a.reports.at(-1)):null,liveReview=a?[...a.mentorReviews].reverse().find(r=>r.status==='Confirmed')??null:null;
 return <div className="c310-feature"><div className="page-head"><div><span className="overline">CONFIDENCE · COGNITION · CONSISTENCY · INDEPENDENT OWNERSHIP</span><h1>My C310 Report</h1><p>Your ratings, examples and next steps — in the Employable Skill Matrix.</p></div><button disabled={busy||loading} onClick={load}><RefreshCw size={17}/>{loading?'Loading…':'Refresh saved data'}</button></div>{error&&<div role="alert" className="error-box"><span>{error} Your open form has been kept.</span></div>}{success&&<div className="c310-success" role="status"><CheckCircle2 size={17}/>{success}</div>}
 {!packet?<section className="card c310-empty"><FileText/><h2>{loading?'Loading your C310 space…':'Reports unavailable'}</h2>{!loading&&<button onClick={load}>Try again</button>}</section>:<><nav className="c310-section-tabs" aria-label="C310 workspace"><button aria-pressed={section==='mine'} onClick={()=>{setSection('mine');setSelected('');setSnapshot('');}}>My assessments</button>{packet.reviewRiders.length>0&&<button aria-pressed={section==='mentor'} onClick={()=>{setSection('mentor');setSelected('');setSnapshot('');}}>Mentor reviews</button>}{user.role==='owner'&&<button aria-pressed={section==='models'} onClick={()=>setSection('models')}>Scoring models</button>}</nav>
 {section==='models'?<><ModelEditor key={packet.models[0].id} model={packet.models[0]} busy={busy} publish={data=>{void send({op:'model',data});}}/><section className="card"><h3>Model history</h3>{packet.models.map(m=><div className="c310-history-row" key={m.id}><strong>{m.version}</strong><span>{pretty(m.createdAt)} · {m.note}</span></div>)}</section></>:<>
 <div className="c310-title-row c310-list-tools"><div><h2>{section==='mentor'?'Assigned rider reviews':'Your assessment history'}</h2>{section==='mentor'&&<p>Assigned riders: {packet.reviewRiders.map(p=>p.name).join(', ')}.</p>}</div>{section==='mine'&&<button className="primary" disabled={busy} onClick={()=>send({op:'new',previousId:null})}><Plus size={17}/>Start assessment</button>}</div>
 {section==='mine'&&<HistoryChart records={mine}/>}
 {visible.length?<div className="c310-history-strip">{visible.map(r=>{const assessment=r.assessment,last=assessment.reports.at(-1);return <button key={assessment.id} aria-pressed={selected===assessment.id} onClick={()=>{setSelected(assessment.id);setSnapshot('');setSuccess('');}}><strong>{section==='mentor'?assessment.riderName+' · ':''}{assessment.answers.subject||'New assessment'}</strong><span>{pretty(assessment.answers.date)} · {assessment.status}</span><span>{last?`${last.source} · Score-B ${fixed(last.scores.scoreB)}`:'Draft · no final score'}</span></button>;})}</div>:<section className="card c310-empty"><FileText/><h3>{section==='mentor'?'No submitted assessments to review yet':'Begin with one honest snapshot'}</h3><p>{section==='mentor'?'Riders submit their own ratings and request review.':'Start an assessment. Save it, collect examples and return when you are ready.'}</p></section>}
 {record&&a&&<>
 {section==='mine'&&a.status==='Draft'?<AssessmentForm key={a.id} record={record} send={send} busy={busy}/>:<>
 {report&&<><div className="c310-report-tools"><Field name="Saved report snapshot"><select value={report.id} onChange={e=>setSnapshot(e.target.value)}>{[...a.reports].reverse().map(r=><option key={r.id} value={r.id}>{r.source} · {pretty(r.generatedAt)} · {r.model.version} · Score-B {fixed(r.scores.scoreB)}</option>)}</select></Field>{section==='mine'&&<><button disabled={busy} onClick={()=>send({op:'request',id:a.id,revision:record.revision})}><MessageSquare size={17}/>Request mentor review</button><button disabled={busy} onClick={()=>send({op:'new',previousId:a.id})}>Start reassessment</button></>}</div><ReportView key={report.id} report={report} liveReview={liveReview}/></>}
 {section==='mentor'&&a.status!=='Draft'&&<div className="c310-mentor-desk"><MentorForm key={a.id} record={record} user={user} send={send} busy={busy}/><div className="c310-two"><CurriculumForm key={a.id+'-curriculum'} record={record} send={send} busy={busy}/><WeekendForm key={a.id+'-weekend'} record={record} send={send} busy={busy} ctx={ctx}/></div>{user.role==='owner'&&<OutcomeForm key={a.id+'-outcome'} record={record} send={send} busy={busy}/>}<details className="card"><summary>Review history · {a.mentorReviews.length} version{a.mentorReviews.length===1?'':'s'}</summary>{a.mentorReviews.map(r=><div className="c310-history-row" key={r.id}><strong>{r.mentorName} · {r.status} · {pretty(r.date)}</strong><p>{r.comment||'Draft observation.'}</p></div>)}</details></div>}
 {section==='mentor'&&a.status==='Draft'&&<section className="card"><h3>Rider draft</h3><p>The rider is still gathering evidence. Independent mentor review becomes available after submission.</p></section>}
 </>}
 </>}
 </>}
 <p className="c310-footnote">{(a?.model??packet.models[0]).factors.filter(f=>f.provisional).map(f=>`${f.code} ${round2(f.p1Share*100)}/${round2(f.p2Share*100)}`).join(' and ')} are provisional working-model settings. Score-A excludes C1B; Score-B includes it. Ownership is a separate project, and certification needs an authorised decision.</p>
 </>}
 </div>;
}
