'use client';
import { useEffect,useMemo,useState } from 'react';
import { TrendingUp,ShieldCheck,RefreshCw,CheckCircle2,Plus } from 'lucide-react';
import { players,attributes,canManageGrowth,emptyDay,emptyReview,riverEnd,weekAt,weekCount,weekDates,reviewDates,ranked,label,dailyBalance,incidentMinutes,incidentAllocated,taskAllowance,type GrowthState,type Player,type Incident,type Catalogue,type Review,type Practice,type TaskSupport,type Support,type Settings } from '../lib/growth';
import { istDate,type Identity } from '../lib/jaguar';
import './growth.css';
type Save=(op:string,data:unknown)=>Promise<boolean>;
type Packet={state:GrowthState;revision:number;updatedAt:string|null};
const tabs=['Dashboard','Daily entry','Incidents','Reviews','Weekly practice','Mistake catalogue','Task support','Setup'] as const;
const num=(s:string)=>s===''?null:Number(s);
const hours=(n:number)=>(n/60).toLocaleString('en-GB',{maximumFractionDigits:2});
const pretty=(s:string)=>new Date(s+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
function Field({name,children,hint}:{name:string;children:React.ReactNode;hint?:string}){return <label className="gt-field"><span>{name}</span>{children}{hint&&<small>{hint}</small>}</label>;}
function NumberBox({value,onChange,max=1440,step=1,label:ariaLabel}:{value:number|null;onChange:(v:number|null)=>void;max?:number;step?:number;label?:string}){return <input type="number" aria-label={ariaLabel} min="0" max={max} step={step} value={value??''} onChange={e=>onChange(num(e.target.value))}/>;}
function Link({url}:{url?:string}){return url?<a className="text-link" href={url} target="_blank" rel="noopener noreferrer">Open exercise</a>:<span className="gt-muted">Exercise link pending</span>;}
function Actions({busy,label:button='Save entry',children}:{busy:boolean;label?:string;children?:React.ReactNode}){return <footer className="gt-actions">{children}<button className="primary" type="submit" disabled={busy}>{busy?'Saving…':button}</button></footer>;}
function AttrSelect({value,onChange,optional=true}:{value:string;onChange:(s:string)=>void;optional?:boolean}){return <select value={value} onChange={e=>onChange(e.target.value)}>{optional&&<option value="">Not attributed</option>}{attributes.map(([id,name])=><option key={id} value={id}>{id} · {name}</option>)}</select>;}
function Metric({value,name}:{value:string;name:string}){return <div><strong>{value}</strong><span>{name}</span></div>;}
function GrowthChart({state,player,asOf}:{state:GrowthState;player:Player;asOf:string}){
 const [trait,setTrait]=useState('mean');
 const rows=reviewDates(state.settings.start).map((planned,stage)=>{const r=state.reviews.find(r=>r.player===player&&r.stage===stage&&r.status==='Confirmed'&&r.date<=asOf);return {stage,planned,date:r?.date,life:r?(trait==='mean'?r.grades.reduce((s,g)=>s+(g.life??0),0)/10:r.grades.find(g=>g.attribute===trait)?.life??null):null,path:r?(trait==='mean'?r.grades.reduce((s,g)=>s+(g.path??0),0)/10:r.grades.find(g=>g.attribute===trait)?.path??null):null};});
 const x=(i:number)=>45+i*85,y=(v:number)=>184-v*30;
 return <figure className="gt-chart"><figcaption>Life and Path across the river <span>Reviewed grades · 0–5</span></figcaption><Field name="Growth factor"><select value={trait} onChange={e=>setTrait(e.target.value)}><option value="mean">All ten attributes · mean grade</option>{attributes.map(([a,name])=><option key={a} value={a}>{a} · {name}</option>)}</select></Field><svg viewBox="0 0 600 225" role="img" aria-label={`${player} ${trait==='mean'?'all ten attributes':trait} Life and Path growth, baseline and six reviews, grades zero to five. Exact values are in the table below.`}>
 {[0,1,2,3,4,5].map(v=><g key={v}><line x1="45" x2="555" y1={y(v)} y2={y(v)} stroke="#dce6ed"/><text x="25" y={y(v)+4}>{v}</text></g>)}
 {rows.map((r,i)=><text key={i} x={x(i)} y="213" textAnchor="middle">{i===0?'Base':`R${i}`}</text>)}
 {(['life','path'] as const).map((key,k)=><g key={key}>{rows.slice(1).map((r,i)=>r[key]!==null&&rows[i][key]!==null?<line key={i} x1={x(i)} x2={x(i+1)} y1={y(rows[i][key]!)} y2={y(r[key]!)} stroke={k?'#bc6d35':'#136880'} strokeWidth="3"/>:null)}{rows.map((r,i)=>r[key]!==null?<circle key={i} cx={x(i)} cy={y(r[key]!)} r={k?4:6} fill={k?'#bc6d35':'#136880'}><title>{`${i===0?'Baseline':`Review ${i}`}: ${key} ${r[key]!.toFixed(2)}`}</title></circle>:null)}</g>)}
 </svg><div className="gt-legend"><span className="life">Life</span><span className="path">Path</span></div>
 {!rows.some(r=>r.life!==null)&&<p className="gt-muted">Confirm baseline grades to begin this student’s growth chart.</p>}
 <details><summary>Review dates and exact grades</summary><div className="gt-scroll"><table><thead><tr><th>Review</th><th>Planned</th><th>Assessed</th><th>Life</th><th>Path</th></tr></thead><tbody>{rows.map(r=><tr key={r.stage}><th>{r.stage===0?'Baseline':`Review ${r.stage}`}</th><td>{pretty(r.planned)}</td><td>{r.date?pretty(r.date):'Not confirmed'}</td><td>{r.life?.toFixed(2)??'—'}</td><td>{r.path?.toFixed(2)??'—'}</td></tr>)}</tbody></table></div></details></figure>;
}
function Dashboard({state,player,asOf,week}:{state:GrowthState;player:Player;asOf:string;week:number}){
 const r=ranked(state,player,asOf),wd=weekDates(state.settings.start,week),focus=ranked(state,player,[asOf,wd.end].sort()[0]),p=state.practices.find(p=>p.player===player&&p.week===week),times=incidentMinutes(state,player,state.settings.start,asOf);
 const confirmed=state.reviews.filter(r=>r.player===player&&r.status==='Confirmed'&&r.date<=asOf),latest=[...confirmed].sort((a,b)=>b.date.localeCompare(a.date)||b.stage-a.stage)[0];
 const crewReported=state.incidents.filter(i=>i.date<=asOf).reduce((n,i)=>n+i.minutes*(i.reportedCount??0),0);
 const unallocated=state.incidents.filter(i=>i.date<=asOf&&!incidentAllocated(i)).length;
 const targets=p?p.targets.map(attribute=>({attribute,grade:focus.current.find(g=>g.attribute===attribute)?.grade??p.c310?.grades.find(g=>g.attribute===attribute)?.grade??null})):focus.targets;
 const weekend=p?.weekend??focus.weekend?.attribute;
 return <><div className="stats-grid gt-metrics"><Metric value={latest?(latest.grades.reduce((n,g)=>n+(g.life??0),0)/10).toFixed(2):'—'} name="Latest Life grade / 5"/><Metric value={latest?(latest.grades.reduce((n,g)=>n+(g.path??0),0)/10).toFixed(2):'—'} name="Latest Path grade / 5"/><Metric value={`${r.current.filter(g=>g.grade!==null).length}/10`} name="Attributes assessed"/><Metric value={`${hours(times.avoidable)} h`} name="Confirmed avoidable loss"/></div>
 <div className="gt-grid"><section className="card"><GrowthChart state={state} player={player} asOf={asOf}/></section><section className="card"><div className="card-head"><h2>Eight weakest attributes</h2><span className="gt-muted">{state.settings.method}</span></div>{r.complete?<ol className="gt-bars">{r.weakest.map(g=><li key={g.attribute}><div><strong>{g.attribute}</strong><span>{label(g.attribute)}</span><b>{g.grade!.toFixed(2)}</b></div><div className="gt-bar-track"><i style={{width:`${g.grade!*20}%`}}/></div></li>)}</ol>:<div className="gt-empty"><TrendingUp/><h3>Baseline comes first</h3><p>Confirm all ten attributes with Life and Path evidence. Empty grades remain unassessed; zero is a real grade.</p></div>}</section></div>
 <div className="gt-grid"><section className="card"><div className="card-head"><div><span className="overline">WEEK {week} · {pretty(wd.start)} – {pretty(wd.end)}</span><h2>One priority at a time</h2></div></div>{targets.length?<><ol className="gt-priorities">{targets.map((t,i)=><li key={t.attribute}><span>{i+1}</span><div><strong>{t.attribute} · {label(t.attribute)}</strong><small>{t.grade===null?'Not assessed':`Priority grade ${t.grade.toFixed(2)} / 5`}</small></div></li>)}</ol><div className="gt-weekend"><span className="overline">WEEKEND FOCUS</span><h3>{weekend} · {label(weekend??'')}</h3><Link url={p?.exerciseUrl||state.settings.exerciseLinks[weekend??'']}/><p>{p?`${p.status}${p.outcome?' · '+p.outcome:''}`:'Practice not recorded yet'}</p></div></>:<p className="gt-muted">Weekly priorities appear after a complete confirmed assessment is available by this week.</p>}<p className="gt-muted">C1 first, then C2, then C3, within the weakest eight. Weekend focus uses the lowest of the selected three.</p>{p&&<p className="gt-muted">Saved practice keeps its selected targets when later reviews arrive.</p>}</section>
 <section className="card"><div className="card-head"><h2>Where support is needed</h2></div><div className="gt-time-totals"><Metric value={`${hours(times.blocked)} h`} name="Confirmed blocked"/><Metric value={`${hours(times.pending)} h`} name="Allocated, pending review"/></div><div className="gt-scroll"><table><thead><tr><th>Week</th><th>Blocked h</th><th>Avoidable h</th><th>Pending h</th></tr></thead><tbody>{Array.from({length:weekCount(state.settings.start)},(_,i)=>i+1).filter(w=>weekDates(state.settings.start,w).start<=asOf).map(w=>{const d=weekDates(state.settings.start,w),t=incidentMinutes(state,player,d.start,[d.end,asOf].sort()[0]);return <tr key={w}><th>W{w}</th><td>{hours(t.blocked)}</td><td>{hours(t.avoidable)}</td><td>{hours(t.pending)}</td></tr>;})}</tbody></table></div><p className="gt-muted">Crew reported: {hours(crewReported)} person-hours across incident reports; {unallocated} incident{unallocated===1?'':'s'} awaiting player allocation. This crew total is separate from {player}’s confirmed hours.</p></section></div>
 <section className="card gt-rules"><h2>Practice, evidence, recovery</h2><p>The first 14 days are a learning baseline. The first-week waiver remains in place. This tracker does not deduct energy or automatically deduct skill grades for lost hours.</p><p>Recover the delayed output and demonstrate a better method in the next round. Weekly support conversations take about ten minutes per student; the twice-monthly formal review can replace that week’s conversation.</p><p>Life and Path use the existing 0–5 rubric. Practice priority is separate from certification scores; independent Ownership and its agreed entry threshold remain unchanged.</p></section></>;
}
function DailyEntry({state,date,save,busy}:{state:GrowthState;date:string;save:Save;busy:boolean}){
 const [draft,setDraft]=useState(()=>structuredClone(state.days.find(d=>d.date===date)??emptyDay(date)));
 const change=(i:number,key:string,value:unknown)=>setDraft(d=>({...d,rows:d.rows.map((r,n)=>n===i?{...r,[key]:value}:r)}));
 return <form onSubmit={async e=>{e.preventDefault();await save('day',draft);}}><div className="gt-section-head"><div><h2>{pretty(date)} · four-player check-in</h2><p>One task per player. Enter minutes, a short result and any actual submitted attempts. Record a shared incident once in Incidents.</p></div></div><div className="gt-daily-grid">{draft.rows.map((r,i)=>{const b=dailyBalance(state,date,r),tasks=state.tasks.filter(t=>t.player===r.player);return <section className="card" key={r.player}><div className="card-head"><h3>{r.player}</h3><span className={`badge ${b.complete&&b.gap===0?'good':'warn'}`}>{!b.complete?'Time incomplete':b.gap===0?'Balanced':`${b.gap} min ${b.gap!<0?'over':'unaccounted'}`}</span></div><div className="gt-form-grid"><Field name="Tracked task"><select value={r.taskId} onChange={e=>{const t=tasks.find(t=>t.id===e.target.value);setDraft(d=>({...d,rows:d.rows.map((row,n)=>n===i?{...row,taskId:e.target.value,task:t?.title??row.task,output:t?.expected??row.output}:row)}));}}><option value="">Unlinked activity</option>{tasks.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></Field><Field name="Main activity"><input value={r.task} maxLength={240} onChange={e=>change(i,'task',e.target.value)}/></Field><Field name="Expected output"><input value={r.output} maxLength={4000} onChange={e=>change(i,'output',e.target.value)}/></Field><Field name="Result / evidence"><input value={r.result} maxLength={4000} onChange={e=>change(i,'result',e.target.value)}/></Field></div><div className="gt-minute-grid">{(['scheduled','breaks','meetings','productive','learning'] as const).map(k=><Field key={k} name={`${k[0].toUpperCase()+k.slice(1)} min`}><NumberBox value={r[k]} onChange={v=>change(i,k,v)}/></Field>)}</div><div className="gt-auto-times"><span>Blocked <b>{b.blocked}m</b></span><span>Avoidable <b>{b.avoidable}m</b></span><span>Pending <b>{b.pending}m</b></span></div><div className="gt-form-grid"><Field name="Activity status"><select value={r.status} onChange={e=>change(i,'status',e.target.value)}>{['Not started','In progress','Completed','Blocked'].map(s=><option key={s}>{s}</option>)}</select></Field><Field name="Attempts submitted"><NumberBox value={r.attempts} max={100} onChange={v=>change(i,'attempts',v??0)}/></Field></div></section>;})}</div><Actions busy={busy} label="Save all four players"><span className="gt-muted">Use 0 for none; leave a time field blank when it is unknown.</span></Actions></form>;
}
function IncidentEditor({state,initial,save,busy}:{state:GrowthState;initial:Incident;save:Save;busy:boolean}){
 const [d,setD]=useState(()=>structuredClone(initial));const patch=(v:Partial<Incident>)=>setD(old=>({...old,...v}));
 return <form className="card gt-editor" onSubmit={e=>{e.preventDefault();void save('incident',d);}}><h2>{state.incidents.some(i=>i.id===d.id)?'Review incident':'Record incident'}</h2><div className="gt-form-grid"><Field name="Date"><input type="date" min={state.settings.start} max={riverEnd(state.settings.start)} required value={d.date} onChange={e=>patch({date:e.target.value})}/></Field><Field name="Catalogue pattern"><select value={d.catalogueId} onChange={e=>{const c=state.catalogue.find(c=>c.id===e.target.value);patch({catalogueId:e.target.value,...(c?{observation:c.pattern,timeType:c.timeType,attribute:c.attribute,supporting:c.supporting,exerciseUrl:c.exerciseUrl,kind:c.attribute?'Mistake':'External blocker'}:{})});}}><option value="">New observable pattern</option>{state.catalogue.map(c=><option key={c.id} value={c.id}>{c.id} · {c.pattern}</option>)}</select></Field><Field name="Observation"><textarea required maxLength={240} value={d.observation} onChange={e=>patch({observation:e.target.value})}/></Field><Field name="Evidence / timestamp"><textarea value={d.evidence} maxLength={4000} onChange={e=>patch({evidence:e.target.value})}/></Field><Field name="Minutes per affected player" hint="Enter the event once. Minutes × affected players = person-hours."><NumberBox value={d.minutes} onChange={v=>patch({minutes:v??0})}/></Field><Field name="Reported player count"><NumberBox max={4} value={d.reportedCount} onChange={v=>patch({reportedCount:v})}/></Field></div>
 <fieldset className="gt-checks"><legend>Affected players</legend>{players.map(p=><label key={p}><input type="checkbox" checked={d.affected.includes(p)} onChange={e=>patch({affected:e.target.checked?[...d.affected,p]:d.affected.filter(x=>x!==p)})}/>{p}</label>)}</fieldset><p className="gt-muted">Reported {hours(d.minutes*(d.reportedCount??0))} person-hours · allocated {hours(d.minutes*d.affected.length)} person-hours · {incidentAllocated(d)?'Count matches':'Resolve allocation before review'}</p>
 <div className="gt-form-grid"><Field name="Time classification" hint="Necessary learning is entered in Daily entry. It is not added twice."><select value={d.timeType} onChange={e=>patch({timeType:e.target.value as Incident['timeType']})}>{['Pending','Blocked','Avoidable','Learning'].map(s=><option key={s}>{s}</option>)}</select></Field><Field name="Cause"><select value={d.kind} onChange={e=>patch({kind:e.target.value as Incident['kind']})}><option>Mistake</option><option>External blocker</option></select></Field><Field name="Primary C310 attribute"><AttrSelect value={d.attribute} onChange={v=>patch({attribute:v as Incident['attribute']})}/></Field><Field name="Review status"><select value={d.status} onChange={e=>patch({status:e.target.value as Incident['status']})}><option>Pending</option><option>Reviewed</option></select></Field><Field name="Learner explanation / attribution reason"><textarea maxLength={4000} value={d.explanation} onChange={e=>patch({explanation:e.target.value})}/></Field><Field name="Output recovery / better method next round"><textarea maxLength={4000} value={d.recovery} onChange={e=>patch({recovery:e.target.value})}/></Field><Field name="Exercise link"><input type="url" maxLength={2048} value={d.exerciseUrl} onChange={e=>patch({exerciseUrl:e.target.value})} placeholder="https://…"/></Field></div>
 <fieldset className="gt-checks"><legend>Supporting attributes (optional)</legend>{attributes.filter(([a])=>a!==d.attribute).map(([a])=><label key={a}><input type="checkbox" checked={d.supporting.includes(a)} onChange={e=>patch({supporting:e.target.checked?[...d.supporting,a]:d.supporting.filter(x=>x!==a)})}/>{a}</label>)}</fieldset>
 {d.catalogueId&&<p className="callout">{state.catalogue.find(c=>c.id===d.catalogueId)?.guidance}</p>}{d.sourceNote&&<p className="callout">{d.sourceNote}</p>}<Actions busy={busy} label="Save incident"/></form>;
}
function Incidents({state,date,save,busy}:{state:GrowthState;date:string;save:Save;busy:boolean}){
 const [selected,setSelected]=useState(''),[newId,setNewId]=useState(()=>crypto.randomUUID());
 const initial=state.incidents.find(i=>i.id===selected)??{id:newId,date,catalogueId:'',observation:'',minutes:0,reportedCount:null,affected:[],timeType:'Pending',kind:'Mistake',attribute:'',supporting:[],status:'Pending',evidence:'',explanation:'',recovery:'',exerciseUrl:'',sourceNote:''} as Incident;
 return <div className="gt-grid gt-editor-grid"><section className="card"><div className="card-head"><h2>Shared incidents</h2><button onClick={()=>{setSelected('');setNewId(crypto.randomUUID());}}><Plus size={16}/>New</button></div><p className="gt-muted">Pending entries keep uncertainty visible. External blockers do not automatically become student skill faults.</p>{[...state.incidents].sort((a,b)=>b.date.localeCompare(a.date)).map(i=><button className={`gt-record ${selected===i.id?'selected':''}`} key={i.id} onClick={()=>setSelected(i.id)}><strong>{i.observation}</strong><span>{pretty(i.date)} · {i.attribute||'No attribution'} · {i.status}</span><span>{i.affected.join(', ')||'Players not allocated'} · {i.minutes} min each</span></button>)}</section><IncidentEditor key={initial.id} state={state} initial={initial} save={save} busy={busy}/></div>;
}
function ReviewEditor({state,player,stage,save,busy}:{state:GrowthState;player:Player;stage:number;save:Save;busy:boolean}){
 const original=state.reviews.find(r=>r.player===player&&r.stage===stage),[d,setD]=useState<Review>(()=>structuredClone(original??emptyReview(player,stage,reviewDates(state.settings.start)[stage])));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();const {reviewer:ignored,...data}=d;void ignored;await save('review',data);};
 return <form className="card gt-editor" onSubmit={submit}><div className="card-head"><h2>{player} · {stage===0?'Baseline':`Review ${stage}`}</h2><span className="badge">{original?.status??'Not recorded'}</span></div><div className="gt-form-grid"><Field name="Actual assessment date"><input type="date" min={state.settings.start} max={riverEnd(state.settings.start)} required value={d.date} onChange={e=>setD({...d,date:e.target.value})}/></Field><Field name="Status"><select value={d.status} onChange={e=>setD({...d,status:e.target.value as Review['status']})}><option disabled={original?.status==='Confirmed'}>Draft</option><option>Confirmed</option></select></Field></div><p className="gt-muted">Use reviewed Life and Path examples, on the existing 0–5 rubric. A blank grade means not assessed. Both grades and review evidence are needed to confirm.</p><div className="gt-scroll"><table className="gt-grade-table"><thead><tr><th>Attribute</th><th>Life / 5</th><th>Path / 5</th><th>Specific evidence / feedback</th></tr></thead><tbody>{d.grades.map((g,i)=><tr key={g.attribute}><th><b>{g.attribute}</b><small>{label(g.attribute)}</small></th><td><NumberBox label={`${g.attribute} Life`} max={5} step={0.1} value={g.life} onChange={v=>setD({...d,grades:d.grades.map((x,n)=>n===i?{...x,life:v}:x)})}/></td><td><NumberBox label={`${g.attribute} Path`} max={5} step={0.1} value={g.path} onChange={v=>setD({...d,grades:d.grades.map((x,n)=>n===i?{...x,path:v}:x)})}/></td><td><input aria-label={`${g.attribute} evidence`} maxLength={4000} value={g.evidence} onChange={e=>setD({...d,grades:d.grades.map((x,n)=>n===i?{...x,evidence:e.target.value}:x)})}/></td></tr>)}</tbody></table></div><Field name="Review evidence and agreed next steps"><textarea value={d.evidence} maxLength={4000} onChange={e=>setD({...d,evidence:e.target.value})}/></Field>{original?.reviewer&&<p className="gt-muted">Last reviewed by {original.reviewer}. Corrections retain the previous confirmed version.</p>}<Actions busy={busy} label="Save review"/></form>;
}
function Reviews({state,player,save,busy}:{state:GrowthState;player:Player;save:Save;busy:boolean}){
 const [stage,setStage]=useState(0);const history=state.reviewHistory.filter(r=>r.player===player);
 return <><div className="gt-stage-tabs" aria-label="Review stage">{reviewDates(state.settings.start).map((d,i)=><button key={i} aria-pressed={stage===i} onClick={()=>setStage(i)}>{i===0?'Baseline':`Review ${i}`}<small>{pretty(d)}</small></button>)}</div><ReviewEditor key={`${player}-${stage}`} state={state} player={player} stage={stage} save={save} busy={busy}/>{history.length>0&&<details className="card"><summary>{history.length} previous confirmed review version{history.length===1?'':'s'}</summary>{history.map((r,i)=><div key={i} className="gt-history"><strong>{r.stage===0?'Baseline':`Review ${r.stage}`} · {pretty(r.date)} · {r.reviewer}</strong><p>{r.evidence}</p><p>{r.grades.map(g=>`${g.attribute}: Life ${g.life}, Path ${g.path}`).join(' · ')}</p></div>)}</details>}</>;
}
function PracticeEditor({state,player,week,save,busy}:{state:GrowthState;player:Player;week:number;save:Save;busy:boolean}){
 const wd=weekDates(state.settings.start,week),cutoff=[wd.end,istDate()].sort()[0],r=ranked(state,player,cutoff),old=state.practices.find(p=>p.player===player&&p.week===week);
 const [d,setD]=useState<Practice>(()=>structuredClone(old??{id:`${player}__${week}`,player,week,targets:r.targets.map(t=>t.attribute),weekend:r.weekend?.attribute??'',status:'Planned',minutes:0,evidence:'',feedback:'',retry:'',outcome:'',support:'',exerciseUrl:state.settings.exerciseLinks[r.weekend?.attribute??'']??''}));
 const patch=(p:Partial<Practice>)=>setD(x=>({...x,...p}));
 if(!old&&!r.complete)return <section className="card gt-empty"><h2>Confirm baseline before practice selection</h2><p>Ten assessed attributes are needed to identify the weakest eight and this week’s three priorities.</p></section>;
 return <form className="card gt-editor" onSubmit={async e=>{e.preventDefault();const {targets:ignored,weekend:ignored2,c310:ignored3,...data}=d;void ignored;void ignored2;void ignored3;await save('practice',data);}}><div className="card-head"><div><span className="overline">{pretty(wd.start)} – {pretty(wd.end)}</span><h2>{player} · week {week}</h2></div><span className="badge">{d.status}</span></div>{d.c310&&<p className="gt-muted">Priority source: {d.c310.source}. C1-first selection from the weakest eight; existing saved targets are retained.</p>}<ol className="gt-priorities">{d.targets.map((a,i)=><li key={a}><span>{i+1}</span><div><strong>{a} · {label(a)}</strong><small>Work on one priority at a time</small></div></li>)}</ol><div className="gt-weekend"><span className="overline">WEEKEND PRACTICE</span><h3>{d.weekend} · {label(d.weekend)}</h3><Link url={d.exerciseUrl}/></div><div className="gt-form-grid"><Field name="Practice status"><select value={d.status} onChange={e=>patch({status:e.target.value as Practice['status']})}><option>Planned</option><option>In progress</option><option>Completed</option></select></Field><Field name="Practice minutes"><NumberBox max={2880} value={d.minutes} onChange={v=>patch({minutes:v??0})}/></Field><Field name="Life application / practice evidence"><textarea value={d.evidence} maxLength={4000} onChange={e=>patch({evidence:e.target.value})}/></Field><Field name="Path retry / recovered output"><textarea value={d.retry} maxLength={4000} onChange={e=>patch({retry:e.target.value})}/></Field><Field name="Leader feedback"><textarea value={d.feedback} maxLength={4000} onChange={e=>patch({feedback:e.target.value})}/></Field><Field name="Demonstrated outcome"><textarea value={d.outcome} maxLength={4000} onChange={e=>patch({outcome:e.target.value})}/></Field><Field name="Help needed next week"><textarea value={d.support} maxLength={4000} onChange={e=>patch({support:e.target.value})}/></Field><Field name="Weekend exercise link"><input type="url" maxLength={2048} value={d.exerciseUrl} onChange={e=>patch({exerciseUrl:e.target.value})}/></Field></div><Actions busy={busy} label="Save weekly practice"><span className="gt-muted">Saving locks this week’s selected targets; later reviews guide later weeks.</span></Actions></form>;
}
function CatalogueEditor({initial,save,busy}:{initial:Catalogue;save:Save;busy:boolean}){
 const [d,setD]=useState(()=>structuredClone(initial)),patch=(p:Partial<Catalogue>)=>setD(x=>({...x,...p}));
 return <form className="card gt-editor" onSubmit={e=>{e.preventDefault();void save('catalogue',d);}}><h2>{d.id.startsWith('M')?d.id:'New pattern'} · reusable cohort learning</h2><Field name="Observable mistake pattern"><textarea required value={d.pattern} maxLength={240} onChange={e=>patch({pattern:e.target.value})}/></Field><div className="gt-form-grid"><Field name="Suggested primary attribute"><AttrSelect value={d.attribute} onChange={v=>patch({attribute:v as Catalogue['attribute']})}/></Field><Field name="Suggested time type"><select value={d.timeType} onChange={e=>patch({timeType:e.target.value as Catalogue['timeType']})}>{['Pending','Blocked','Avoidable','Learning'].map(t=><option key={t}>{t}</option>)}</select></Field><Field name="Attribution guidance"><textarea maxLength={4000} value={d.guidance} onChange={e=>patch({guidance:e.target.value})}/></Field><Field name="Next-step practice guidance"><textarea maxLength={4000} value={d.nextStep} onChange={e=>patch({nextStep:e.target.value})}/></Field><Field name="Exercise link"><input type="url" maxLength={2048} value={d.exerciseUrl} onChange={e=>patch({exerciseUrl:e.target.value})}/></Field></div><fieldset className="gt-checks"><legend>Supporting attributes</legend>{attributes.filter(([a])=>a!==d.attribute).map(([a])=><label key={a}><input type="checkbox" checked={d.supporting.includes(a)} onChange={e=>patch({supporting:e.target.checked?[...d.supporting,a]:d.supporting.filter(x=>x!==a)})}/>{a}</label>)}</fieldset><Actions busy={busy} label="Save catalogue pattern"/></form>;
}
function CatalogueDesk({state,save,busy}:{state:GrowthState;save:Save;busy:boolean}){
 const [chosen,setChosen]=useState(state.catalogue[0]?.id??''),[newId,setNewId]=useState(()=>crypto.randomUUID()),[query,setQuery]=useState('');
 const initial=state.catalogue.find(c=>c.id===chosen)??{id:newId,pattern:'',timeType:'Pending',attribute:'',guidance:'',supporting:[],exerciseUrl:'',nextStep:''} as Catalogue;
 return <div className="gt-grid gt-editor-grid"><section className="card"><div className="card-head"><h2>Mistake bank · {state.catalogue.length}</h2><button onClick={()=>{setChosen('');setNewId(crypto.randomUUID());}}><Plus size={16}/>Add</button></div><Field name="Find a pattern or attribute"><input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></Field>{state.catalogue.filter(c=>(c.pattern+c.attribute+c.id).toLowerCase().includes(query.toLowerCase())).map(c=><button className={`gt-record ${chosen===c.id?'selected':''}`} key={c.id} onClick={()=>setChosen(c.id)}><strong>{c.id} · {c.pattern}</strong><span>{c.attribute||'External / review needed'} · {state.incidents.filter(i=>i.catalogueId===c.id).length} observed incidents</span></button>)}</section><CatalogueEditor key={initial.id} initial={initial} save={save} busy={busy}/></div>;
}
function SettingsForm({state,save,busy}:{state:GrowthState;save:Save;busy:boolean}){
 const [d,setD]=useState<Settings>(()=>structuredClone(state.settings));
 return <form className="card gt-editor" onSubmit={e=>{e.preventDefault();void save('settings',d);}}><h2>Three-month river settings</h2><div className="gt-form-grid"><Field name="River start"><input type="date" required value={d.start} onChange={e=>{if(e.target.value)setD({...d,start:e.target.value});}}/></Field><Field name="River end"><output>{d.start?pretty(riverEnd(d.start)):'Choose a start date'}</output></Field><Field name="Practice-priority method"><select value={d.method} onChange={e=>setD({...d,method:e.target.value as Settings['method']})}>{['Lower grade','Life','Path','Weighted'].map(m=><option key={m}>{m}</option>)}</select></Field><Field name="Weighted Life share (0–1)"><NumberBox max={1} step={0.01} value={d.lifeShare} onChange={v=>setD({...d,lifeShare:v})}/></Field><Field name="Approved base attempts" hint="Leave blank until the policy is approved."><NumberBox max={100} value={d.baseAttempts} onChange={v=>setD({...d,baseAttempts:v})}/></Field></div><details><summary>Default exercise links by attribute</summary><div className="gt-form-grid">{attributes.map(([a,name])=><Field key={a} name={`${a} · ${name}`}><input type="url" maxLength={2048} value={d.exerciseLinks[a]??''} onChange={e=>setD({...d,exerciseLinks:{...d.exerciseLinks,[a]:e.target.value}})}/></Field>)}</div></details><p className="gt-muted">Lower grade selects the weaker Life / Path grade. These formulas guide practice; they do not change the existing certification weights or Ownership threshold.</p><Actions busy={busy} label="Save settings"/></form>;
}
function SupportForm({initial,save,busy}:{initial:Support;save:Save;busy:boolean}){
 const [d,setD]=useState(()=>structuredClone(initial));
 return <form className="card gt-editor" onSubmit={e=>{e.preventDefault();void save('support',d);}}><div className="card-head"><h3>{d.player}</h3><span className={`badge ${d.approved?'good':''}`}>{d.approved?'Approved':'Pending'}</span></div><div className="gt-form-grid"><Field name="Provisional starting order"><NumberBox max={4} value={d.order} onChange={v=>setD({...d,order:v??1})}/></Field><Field name="Earns while studying"><select value={d.earns} onChange={e=>setD({...d,earns:e.target.value as Support['earns']})}><option>Not recorded</option><option>Yes</option><option>No</option></select></Field></div><Field name="Known responsibilities"><textarea value={d.responsibilities} maxLength={4000} onChange={e=>setD({...d,responsibilities:e.target.value})}/></Field><div className="gt-form-grid"><Field name="Extra days"><NumberBox max={90} value={d.extraDays} onChange={v=>setD({...d,extraDays:v})}/></Field><Field name="Extra attempts"><NumberBox max={90} value={d.extraAttempts} onChange={v=>setD({...d,extraAttempts:v})}/></Field></div><Field name="Allowance basis / agreed support"><textarea value={d.basis} maxLength={4000} onChange={e=>setD({...d,basis:e.target.value})}/></Field><label className="gt-check"><input type="checkbox" checked={d.approved} onChange={e=>setD({...d,approved:e.target.checked})}/>Approve both allowances</label><Actions busy={busy} label={`Save ${d.player} support`}/></form>;
}
function Setup({state,save,busy}:{state:GrowthState;save:Save;busy:boolean}){return <><SettingsForm state={state} save={save} busy={busy}/><div className="gt-section-head"><div><h2>Responsibility and opportunity support</h2><p>Starting order is provisional time flexibility. Discuss actual earning and caring commitments. Approve extra time and extra attempts together; the skill standard stays the same.</p></div></div><div className="gt-daily-grid">{state.supports.map(s=><SupportForm key={s.player} initial={s} save={save} busy={busy}/>)}</div><section className="card gt-rules"><h2>Assessment rhythm</h2><p>Baseline plus six formal reviews: twice a month, over three calendar months. A short weekly support conversation identifies the next three priorities. Weekend practice targets the lowest selected grade.</p><p>Entry point held for the later framework: reasonably decent C310 Part 1 skills and specialised C310 training before entering the river.</p><p>Private Growth Tracker access: Team Leader Premothan and Cohort Leader Lavy.</p></section><section className="card"><details><summary>Supplied tracker observations · preserved source</summary><p className="gt-muted">DAY_Gamer_Tracker_v2.xlsx · No personal time allocation or grades have been inferred from these rows. The original practice assignments remain source evidence; current practice uses the weekly selection.</p><div className="gt-scroll"><table><thead><tr><th>Date</th><th>Total h</th><th>Break h</th><th>Meeting h</th><th>Working h</th><th>Reported loss h</th><th>Remaining h</th><th>Surjith work h</th><th>Abinesh work h</th></tr></thead><tbody>{state.sourceObservations.map(s=><tr key={s.date}><th>{pretty(s.date)}</th>{[s.total,s.breaks,s.meetings,s.working,s.reportedLoss,s.remaining,s.surjithWork,s.abineshWork].map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div>{state.sourceObservations.map(s=><details key={s.date}><summary>{pretty(s.date)} · original observations</summary><p className="preserve-lines">{s.note}</p></details>)}</details></section></>;}
function TaskEditor({initial,state,save,busy,projectTasks}:{initial:TaskSupport;state:GrowthState;save:Save;busy:boolean;projectTasks:ProjectTask[]}){
 const [d,setD]=useState(()=>structuredClone(initial));const a=taskAllowance(state,d);
 return <form className="card gt-editor" onSubmit={e=>{e.preventDefault();void save('task',d);}}><h2>Task deadline and attempts</h2><Field name="Use an existing project task (optional)"><select value="" onChange={e=>{const t=projectTasks.find(t=>t.id===e.target.value);if(t)setD({...d,id:t.id,title:t.title,expected:t.criteria,due:t.due,player:t.player});}}><option value="">Choose to copy its task details</option>{projectTasks.map(t=><option key={t.id} value={t.id}>{t.player} · {t.title}</option>)}</select></Field><div className="gt-form-grid"><Field name="Player"><select value={d.player} onChange={e=>setD({...d,player:e.target.value as Player})}>{players.map(p=><option key={p}>{p}</option>)}</select></Field><Field name="Base deadline"><input type="date" min={state.settings.start} max={riverEnd(state.settings.start)} required value={d.due} onChange={e=>{if(e.target.value)setD({...d,due:e.target.value});}}/></Field><Field name="Task title"><input required value={d.title} maxLength={240} onChange={e=>setD({...d,title:e.target.value})}/></Field><Field name="Expected output"><input required value={d.expected} maxLength={4000} onChange={e=>setD({...d,expected:e.target.value})}/></Field><Field name="Extra-day override" hint="Blank uses approved player support; 0 overrides it."><NumberBox max={90} value={d.extraDays} onChange={v=>setD({...d,extraDays:v})}/></Field><Field name="Extra-attempt override"><NumberBox max={90} value={d.extraAttempts} onChange={v=>setD({...d,extraAttempts:v})}/></Field></div><Field name="Override reason"><textarea value={d.reason} maxLength={4000} onChange={e=>setD({...d,reason:e.target.value})}/></Field><div className="gt-auto-times"><span>Adjusted due <b>{a.due?pretty(a.due):'Awaiting approval'}</b></span><span>Allowed <b>{a.allowed??'Awaiting approval'}</b></span><span>Submitted <b>{a.attempts}</b></span><span>Remaining <b>{a.remaining??'—'}</b></span></div><p className="gt-muted">Daily entry counts actual submitted attempts. Allowances do not silently change a shared project task’s deadline; use the adjusted deadline in the agreed plan.</p><Actions busy={busy} label="Save tracked task"/></form>;
}
type ProjectTask={id:string;player:Player;title:string;criteria:string;due:string};
function TasksDesk({state,save,busy,date,projectTasks}:{state:GrowthState;save:Save;busy:boolean;date:string;projectTasks:ProjectTask[]}){
 const [selected,setSelected]=useState(''),[newId,setNewId]=useState(()=>crypto.randomUUID());const initial=state.tasks.find(t=>t.id===selected)??{id:newId,player:'Abinesh',title:'',expected:'',due:date,extraDays:null,extraAttempts:null,reason:''} as TaskSupport;
 return <div className="gt-grid gt-editor-grid"><section className="card"><div className="card-head"><h2>Tracked task allowances</h2><button onClick={()=>{setSelected('');setNewId(crypto.randomUUID());}}><Plus size={16}/>New</button></div>{state.tasks.length?state.tasks.map(t=>{const a=taskAllowance(state,t);return <button className={`gt-record ${selected===t.id?'selected':''}`} key={t.id} onClick={()=>setSelected(t.id)}><strong>{t.player} · {t.title}</strong><span>Due {a.due?pretty(a.due):'awaiting approval'} · {a.attempts}/{a.allowed??'—'} attempts submitted</span></button>}):<p className="gt-muted">Add a task or copy an existing project task. Once support is approved, adjusted dates and attempt limits calculate automatically.</p>}</section><TaskEditor key={initial.id} initial={initial} state={state} save={save} busy={busy} projectTasks={projectTasks}/></div>;
}
export default function GrowthTracker({user,projectTasks=[]}:{user:Identity;projectTasks?:ProjectTask[]}){
 const [packet,setPacket]=useState<Packet|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(''),[tab,setTab]=useState<typeof tabs[number]>('Dashboard'),[player,setPlayer]=useState<Player>('Abinesh'),[asOf,setAsOf]=useState(istDate()),[day,setDay]=useState(istDate()),[week,setWeek]=useState<number|null>(null);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/growth',{cache:'no-store'}),b=await r.json() as Packet&{error?:string};if(!r.ok)throw new Error(b.error??'Could not load Growth Tracker.');setPacket(b);}catch(e){setError(e instanceof Error?e.message:'Could not load Growth Tracker.');}finally{setLoading(false);}}
 useEffect(()=>{if(canManageGrowth(user))void load();},[user.email]);
 const state=packet?.state,focusWeek=state?Math.max(1,Math.min(weekCount(state.settings.start),week??weekAt(state.settings.start,asOf))):1;
 const projectEnd=state?riverEnd(state.settings.start):'';
 const safeDay=state?[day,state.settings.start,projectEnd].sort()[1]:day;
 const visibleTasks=useMemo(()=>projectTasks,[projectTasks]);
 const save:Save=async(op,data)=>{if(!packet||busy)return false;setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/growth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op,revision:packet.revision,data})}),b=await r.json() as Packet&{error?:string};if(!r.ok)throw new Error(b.error??'Could not save. Your draft has been kept.');setPacket(b);setSuccess('Saved to Growth Tracker.');return true;}catch(e){setError(e instanceof Error?e.message:'Could not save. Your draft has been kept.');return false;}finally{setBusy(false);}};
 if(!canManageGrowth(user))return <section className="card"><h1>Growth Tracker is private</h1><p>Only Premothan and Lavy can open student tracking records.</p></section>;
 return <div className="growth-tracker"><div className="page-head"><div><span className="overline">JAGUAR CREW · THREE-MONTH RIVER</span><h1>Student growth</h1>{state&&<p>{pretty(state.settings.start)} – {pretty(projectEnd)} · Life and Path · ten C310 attributes</p>}</div><span className="launch-tag"><ShieldCheck size={16}/>Premothan & Lavy only</span></div>
 {error&&<div className="error-box" role="alert"><span>{error} Your open entry has been kept.</span><button disabled={busy} onClick={load}>Reload saved data</button></div>}{success&&<div className="gt-success" role="status"><CheckCircle2 size={16}/>{success}</div>}
 {!state?<section className="card gt-empty"><TrendingUp/><h2>{loading?'Loading student tracker…':'Tracker unavailable'}</h2>{!loading&&<button onClick={load}>Try again</button>}</section>:<><div className="gt-tabs" role="tablist" aria-label="Growth Tracker sections">{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} aria-controls="gt-panel" onClick={()=>{setTab(t);setSuccess('');}}>{t}</button>)}</div><div className="gt-toolbar">
 {['Dashboard','Reviews','Weekly practice'].includes(tab)&&<Field name="Student"><select value={player} onChange={e=>setPlayer(e.target.value as Player)}>{players.map(p=><option key={p}>{p}</option>)}</select></Field>}
 {tab==='Dashboard'&&<Field name="As of"><input type="date" min={state.settings.start} max={projectEnd} value={asOf} onChange={e=>{if(e.target.value){setAsOf(e.target.value);setWeek(null);}}}/></Field>}
 {tab==='Daily entry'&&<Field name="Activity date"><input type="date" min={state.settings.start} max={projectEnd} value={safeDay} onChange={e=>{if(e.target.value)setDay(e.target.value);}}/></Field>}
 {['Dashboard','Weekly practice'].includes(tab)&&<Field name="Focus week"><select value={focusWeek} onChange={e=>setWeek(Number(e.target.value))}>{Array.from({length:weekCount(state.settings.start)},(_,i)=>i+1).map(w=><option value={w} key={w} disabled={weekDates(state.settings.start,w).start>asOf}>Week {w} · {pretty(weekDates(state.settings.start,w).start)}</option>)}</select></Field>}
 <button className="gt-reload" disabled={busy||loading} onClick={load}><RefreshCw size={16}/>{loading?'Refreshing…':'Refresh'}</button>{packet?.updatedAt&&<span className="gt-muted">Last saved {new Date(packet.updatedAt).toLocaleString('en-GB',{timeZone:'Asia/Kolkata'})} IST</span>}
 </div><div id="gt-panel" role="tabpanel">
 {tab==='Dashboard'&&<Dashboard state={state} player={player} asOf={asOf} week={focusWeek}/>}
 {tab==='Daily entry'&&<DailyEntry key={safeDay} state={state} date={safeDay} save={save} busy={busy}/>}
 {tab==='Incidents'&&<Incidents state={state} date={safeDay} save={save} busy={busy}/>}
 {tab==='Reviews'&&<Reviews state={state} player={player} save={save} busy={busy}/>}
 {tab==='Weekly practice'&&<PracticeEditor key={`${player}-${focusWeek}`} state={state} player={player} week={focusWeek} save={save} busy={busy}/>}
 {tab==='Mistake catalogue'&&<CatalogueDesk state={state} save={save} busy={busy}/>}
 {tab==='Task support'&&<TasksDesk state={state} save={save} busy={busy} date={safeDay} projectTasks={visibleTasks}/>}
 {tab==='Setup'&&<Setup state={state} save={save} busy={busy}/>}
 </div></>}
 </div>;
}
