import { database,RequestError } from './crew-server';
import { initialModel,canAccess,canReview,riderPlayer,type Assessment,type AssessmentRecord,type Model,type Context,type CurriculumRef } from './c310-model';
import { type Identity } from './jaguar';
import { type GrowthState } from './growth';
export async function models(){const db=await database();await db.models.updateOne({_id:initialModel.id},{$setOnInsert:{_id:initialModel.id,id:initialModel.id,data:initialModel,created_at:initialModel.createdAt}},{upsert:true});return (await db.models.find({}).sort({created_at:-1,id:-1}).limit(100).toArray()).map(r=>r.data);}
export async function assessment(id:string,u:Identity):Promise<AssessmentRecord>{const row=await (await database()).assessments.findOne({_id:id});if(!row)throw new RequestError('Assessment not found.',404);const a=row.data;if(!canAccess(u,a))throw new RequestError('You cannot open another rider’s assessment.',403);return {assessment:a,revision:row.revision,updatedAt:row.updated_at};}
export async function assessmentList(u:Identity){const emails=[...new Set([u.email,...(await import('./jaguar')).crew.filter(c=>canReview(u,c.email)).map(c=>c.email)])];return (await (await database()).assessments.find({rider:{$in:emails}}).sort({created_at:-1}).limit(200).toArray()).map(r=>({assessment:r.data,revision:r.revision,updatedAt:r.updated_at}));}
export async function store(a:Assessment,revision:number){const now=new Date().toISOString(),result=await (await database()).assessments.updateOne({_id:a.id,revision},{$set:{data:a,updated_at:now},$inc:{revision:1}});if(result.modifiedCount!==1)throw new RequestError('This assessment changed. Reload saved data, then save your kept draft again.',409);return {assessment:a,revision:revision+1,updatedAt:now};}
export async function context(a:Assessment):Promise<Context>{
 const row=await (await database()).growth.findOne({_id:'jaguar'}),growth=row?.data??null,p=riderPlayer(a.rider);
 const latest=new Map<string,CurriculumRef>();for(const c of a.curriculum)latest.set(`${c.code}_${c.part}`,c);
 if(growth)for(const f of a.model.factors){const url=growth.settings.exerciseLinks[f.code];if(url)for(const part of [1,2] as const)if(!latest.has(`${f.code}_${part}`))latest.set(`${f.code}_${part}`,{id:`growth_${f.code}_${part}`,code:f.code,part,title:`C310 curriculum · ${f.code}`,url,note:'Existing factor-level mapping. Confirm the activity’s Part 1 / Part 2 relevance with your mentor.',by:'Existing curriculum mapping',assignedAt:''});}
 const work=p&&growth?growth.incidents.filter(i=>i.status==='Reviewed'&&i.affected.includes(p)).flatMap(i=>[i.attribute,...i.supporting].filter(Boolean).map(attribute=>({id:`${i.id}_${attribute}`,date:i.date,attribute,observation:i.observation,evidence:i.evidence,recovery:i.recovery}))).concat(growth.days.flatMap(d=>d.rows.filter(r=>r.player===p&&r.result).map(r=>({id:`${d.date}_${p}`,date:d.date,attribute:'',observation:r.task,evidence:r.result,recovery:''})))):[];
 const weekly=p&&growth?growth.practices.filter(w=>w.player===p).map(w=>({week:w.week,targets:w.targets,weekend:w.weekend,status:w.status,exerciseUrl:w.exerciseUrl,basis:w.c310?.source??'Existing leader tracker grades'})):[];
 return {riverStart:growth?.settings.start??'2026-10-03',riverWeeks:growth?(await import('./growth')).weekCount(growth.settings.start):14,work:work.sort((x,y)=>x.date.localeCompare(y.date)||x.id.localeCompare(y.id)).slice(-80),weekly,curriculum:[...latest.values()]};
}
export const c310Failure=(e:unknown)=>{if(e instanceof RequestError)return Response.json({error:e.message},{status:e.status,headers:{'Cache-Control':'private, no-store'}});console.error('C310 request failed',e instanceof Error?e.name:'unknown');return Response.json({error:'C310 could not load or save. Your open draft has been kept. Try again shortly.'},{status:503,headers:{'Cache-Control':'private, no-store'}});};
