import { crew,type Identity } from './jaguar';
import { attributes,players,type Attribute,type Player } from './growth';
export type Part=1|2;
export type Factor={code:Attribute;name:string;weight:number;p1Share:number;p2Share:number;p1:string;p2:string;provisional:boolean};
export type Model={id:string;version:string;createdAt:string;factors:Factor[];gate:{scoreA:number;c1aP1:number;c1cP1:number;c1cP2:number;c2bP2:number};cert:{c1bLevel:number;scoreB:number};note:string};
export const initialModel:Model={id:'c310-working-2026-10-v1',version:'Working model 2026.10 · v1',createdAt:'2026-10-06T00:00:00Z',note:'Provisional development model. C1B 60/40 and C3B 30/70 are working settings. Ownership is assessed separately through a project.',
 factors:[
 {code:'C1A',name:'Communication confidence',weight:9,p1Share:.4,p2Share:.6,p1:'Ask for help, clarify or report mistakes in everyday settings.',p2:'Explain chosen-subject work to the person who needs it.',provisional:false},
 {code:'C1B',name:'Social and institutional confidence',weight:10,p1Share:.6,p2Share:.4,p1:'Participate and act in unfamiliar social or institutional settings.',p2:'Navigate workplace roles, routines, relationships and unwritten rules.',provisional:true},
 {code:'C1C',name:'Opportunity and economic agency',weight:8,p1Share:.5,p2Share:.5,p1:'Recognise and compare opportunities, costs, risks and support.',p2:'Take a feasible, observable step towards the chosen route.',provisional:false},
 {code:'C1D',name:'Self-belief and recovery',weight:8,p1Share:.6,p2Share:.4,p1:'Recognise setbacks, seek support and re-engage over time.',p2:'Return to chosen-subject work after feedback or an error.',provisional:false},
 {code:'C2A',name:'Subject cognition',weight:12,p1Share:.3,p2Share:.7,p1:'Understand users and the real-world impact of application errors.',p2:'Understand the chosen subject or application in depth.',provisional:false},
 {code:'C2B',name:'Applied problem solving',weight:12,p1Share:.7,p2Share:.3,p1:'Define problems, check evidence and reason through causes without AI.',p2:'Apply reasoning to chosen-subject problems.',provisional:false},
 {code:'C2C',name:'People, context and requirements',weight:10,p1Share:.4,p2Share:.6,p1:'Notice people’s needs, missing context and assumptions.',p2:'Identify and reconcile requirements across relevant business processes.',provisional:false},
 {code:'C2D',name:'AI as a learning and work aide',weight:9,p1Share:.4,p2Share:.6,p1:'Write, refine and verify prompts and AI answers.',p2:'Reduce subject workload with AI while keeping independent judgement.',provisional:false},
 {code:'C3A',name:'Cognitive practice consistency',weight:11,p1Share:.5,p2Share:.5,p1:'Repeat agreed reasoning, reflection and feedback practice.',p2:'Practise thinking on chosen-subject problems over time.',provisional:false},
 {code:'C3B',name:'Subject practice consistency',weight:11,p1Share:.3,p2Share:.7,p1:'Continue agreed study, practical work and communication.',p2:'Produce, explain and improve chosen-subject work over time.',provisional:true},
 ],gate:{scoreA:70,c1aP1:2,c1cP1:2,c1cP2:1.5,c2bP2:2.5},cert:{c1bLevel:80,scoreB:70}};
export const rubric=[['0','Not demonstrated in an observed opportunity'],['1','Completes parts with substantial support'],['2','Demonstrates with prompts or repeated support'],['3','Works independently in a familiar setting'],['4','Adapts, explains and checks in different settings'],['5','Repeatedly transfers, validates and improves with evidence']];
export type Rating={code:Attribute;p1:number|null;p2:number|null;e1:string;e2:string};
export type Answers={subject:string;path:string;date:string;ratings:Rating[];barriers:string;support:string;reflection:string};
export type MentorReview={id:string;mentor:string;mentorName:string;date:string;status:'Draft'|'Confirmed';ratings:Rating[];comment:string;factorComments:Record<string,string>};
export type CurriculumRef={id:string;code:Attribute;part:Part;title:string;url:string;note:string;by:string;assignedAt:string};
export type Outcome={id:string;project:'Not assessed'|'Passed'|'Needs further work';evidence:string;certified:boolean;by:string;date:string};
export type WorkEvidence={id:string;date:string;attribute:string;observation:string;evidence:string;recovery:string};
export type WeeklyLink={week:number;targets:Attribute[];weekend:string;status:string;exerciseUrl:string;basis:string};
export type Context={riverStart?:string;riverWeeks?:number;work:WorkEvidence[];weekly:WeeklyLink[];curriculum:CurriculumRef[]};
export type FactorResult=Omit<Factor,'p1'|'p2'>&{p1Definition:string;p2Definition:string;p1:number|null;p2:number|null;blended:number|null;level:number|null;points:number|null;gap:number|null};
export type Requirement={label:string;met:boolean|null;code?:Attribute;part?:Part};
export type Scores={complete:boolean;scoreA:number|null;scoreB:number|null;denominatorA:number;factors:FactorResult[];gate:boolean|null;gateRequirements:Requirement[];cert:boolean|null;certRequirements:Requirement[]};
export type Priority={code:Attribute;part:Part;name:string;level:number;gap:number;why:string;interpretation:string;do:string;avoid:string;proof:string;source:string[];references:CurriculumRef[]};
export type Report={id:string;assessmentId:string;rider:string;riderName:string;source:'Self-rated'|'Mentor-rated';reviewer:string;reviewDate:string|null;generatedAt:string;model:Model;answers:Answers;selfRatings:Rating[];mentorRatings:Rating[]|null;outcome:Outcome|null;scores:Scores;summary:string;priorities:Priority[];supporting:Priority[];strengths:Priority[];context:Context;weekend:{weakest:Attribute[];targets:Attribute[];weekend:Attribute|''};reviewCycle:{week:string;action:string}[];mentorComments:string};
export type Assessment={id:string;rider:string;riderName:string;model:Model;answers:Answers;status:'Draft'|'Submitted'|'Review requested'|'Reviewed';mentorReviews:MentorReview[];curriculum:CurriculumRef[];outcomes:Outcome[];reports:Report[];createdAt:string;previousId:string|null};
export type AssessmentRecord={assessment:Assessment;revision:number;updatedAt:string};
export const round2=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export const emptyRatings=():Rating[]=>attributes.map(([code])=>({code,p1:null,p2:null,e1:'',e2:''}));
export const canReview=(u:Identity,target:string,roster:readonly Identity[]=crew)=>u.email!==target&&(u.role==='owner'||u.role==='cohort_leader'&&roster.some(c=>c.email===target&&c.role==='learner'));
export const canAccess=(u:Identity,a:Assessment,roster:readonly Identity[]=crew)=>a.rider===u.email||canReview(u,a.rider,roster);
export const riderPlayer=(email:string):Player|null=>{const p=crew.find(p=>p.email===email)?.name.split(' ')[0];return players.includes(p as Player)?p as Player:null;};
export function calculate(model:Model,ratings:Rating[],outcome:Outcome|null=null):Scores{
 const factors=model.factors.map(f=>{const r=ratings.find(r=>r.code===f.code);const p1=r?.p1??null,p2=r?.p2??null,blended=p1===null||p2===null?null:p1*f.p1Share+p2*f.p2Share;return {...f,p1Definition:f.p1,p2Definition:f.p2,p1,p2,blended,level:blended===null?null:blended*20,points:blended===null?null:blended/5*f.weight,gap:blended===null?null:f.weight-blended/5*f.weight};});
 const complete=factors.every(f=>f.blended!==null),denominatorA=model.factors.filter(f=>f.code!=='C1B').reduce((n,f)=>n+f.weight,0);
 const scoreB=complete?round2(factors.reduce((n,f)=>n+f.points!,0)):null,scoreA=complete?round2(factors.filter(f=>f.code!=='C1B').reduce((n,f)=>n+f.points!,0)/denominatorA*100):null;
 const value=(code:Attribute,part:Part)=>factors.find(f=>f.code===code)![part===1?'p1':'p2'];
 const minimum=(code:Attribute,part:Part,min:number):Requirement=>({label:`${code} Part ${part} ≥ ${min}/5`,code,part,met:complete?value(code,part)!>=min:null});
 const gateRequirements:Requirement[]=[{label:`Score-A ≥ ${model.gate.scoreA}`,met:complete?scoreA!>=model.gate.scoreA:null},minimum('C1A',1,model.gate.c1aP1),minimum('C1C',1,model.gate.c1cP1),minimum('C1C',2,model.gate.c1cP2),minimum('C2B',2,model.gate.c2bP2)];
 const gate=complete?gateRequirements.every(r=>r.met):null;
 const c1b=factors.find(f=>f.code==='C1B')!,certRequirements:Requirement[]=[{label:'Ownership-entry requirements met',met:gate},{label:`C1B factor level ≥ ${model.cert.c1bLevel}%`,code:'C1B',met:complete?c1b.level!+1e-9>=model.cert.c1bLevel:null},{label:`Score-B ≥ ${model.cert.scoreB}`,met:complete?scoreB!>=model.cert.scoreB:null},{label:'Ownership project passed by an authorised reviewer',met:complete?outcome?.project==='Passed':null}];
 return {complete,scoreA,scoreB,denominatorA,factors,gate,gateRequirements,cert:complete?certRequirements.every(r=>r.met):null,certRequirements};
}
const guidance:Record<Attribute,[{do:string;avoid:string;proof:string},{do:string;avoid:string;proof:string}]>={
 C1A:[{do:'Ask one clear question or report a mistake with the context and help needed.',avoid:'Waiting for a perfect delivery before asking for help.',proof:'An example where the listener understood the question and the next step.'},{do:'Explain the result, why it matters and what the recipient needs to do.',avoid:'Detail that hides the decision, or judging delivery by accent or fluency.',proof:'The recipient can restate the decision and act on it.'}],
 C1B:[{do:'Plan a question or contribution for an unfamiliar setting, with agreed support.',avoid:'Treating unfamiliarity or exclusion as a lack of effort.',proof:'A participation example, the support used and the action taken.'},{do:'Check who owns a decision, the appropriate channel and the expected routine.',avoid:'Guessing unwritten expectations without checking.',proof:'A workplace interaction with the role, routine and outcome recorded.'}],
 C1C:[{do:'Compare a real opportunity’s costs, risks, support and fit with your needs.',avoid:'Choosing only on prestige, or ignoring financial and caring constraints.',proof:'A brief comparison showing a feasible option and the support needed.'},{do:'Take one agreed, feasible step towards your route and record the result.',avoid:'A large plan with no observable next step.',proof:'An action completed, an outcome and a reviewed next step.'}],
 C1D:[{do:'Name the setback, choose support and agree a manageable return step.',avoid:'Interpreting one difficult day as a fixed personality trait.',proof:'Examples across time of seeking support and re-engaging.'},{do:'Use feedback to correct one piece of subject work, then retry.',avoid:'Reworking everything at once or hiding errors.',proof:'Before-and-after work, the feedback used and the return to the task.'}],
 C2A:[{do:'Trace who is affected by an application error and what changes for them.',avoid:'Knowing the feature while overlooking the user’s consequence.',proof:'A user-impact explanation tied to an actual or synthetic error.'},{do:'Explain a subject concept, apply it and check it against a reliable source.',avoid:'Repeating terminology without demonstrating its application.',proof:'Correct work and an explanation of the underlying subject model.'}],
 C2B:[{do:'Define the problem, gather evidence and test causes before asking AI.',avoid:'Accepting the first explanation or outsourcing the reasoning.',proof:'Your own problem statement, alternative causes and a check that distinguishes them.'},{do:'Apply your reasoning to a subject problem and validate the result.',avoid:'Choosing a solution before confirming the subject constraints.',proof:'A solution with its assumptions, reasoning and independent validation.'}],
 C2C:[{do:'Ask whose needs are missing and which assumption needs checking.',avoid:'Assuming the request tells the whole story.',proof:'A clarification that changed or confirmed your understanding of a person’s needs.'},{do:'Reconcile requirements, affected processes and acceptance criteria.',avoid:'Optimising one process while missing its effect on another.',proof:'A requirement trace, resolved conflict and agreed acceptance criteria.'}],
 C2D:[{do:'Refine a prompt, inspect assumptions and verify the answer independently.',avoid:'Treating fluent AI output as evidence of correctness.',proof:'Prompt revisions, verification and your reason to accept or reject the answer.'},{do:'Use AI for a suitable subject step, then review the output yourself.',avoid:'Uploading confidential information or skipping independent judgement.',proof:'A workload comparison and a record of errors you checked or corrected.'}],
 C3A:[{do:'Keep a manageable reasoning and reflection routine with feedback.',avoid:'A large burst of practice followed by an unreviewed gap.',proof:'Brief examples across several dates showing reflection and an adjustment.'},{do:'Practise reasoning on subject problems over time and review changes.',avoid:'Repeating a method without checking whether it improves the result.',proof:'Dated work showing how feedback changed the method.'}],
 C3B:[{do:'Agree a sustainable study, practical work and communication rhythm.',avoid:'Counting hours alone as proof of useful practice.',proof:'Dated participation and work, including the support needed to sustain it.'},{do:'Produce, explain and improve subject work over repeated cycles.',avoid:'Treating completion as enough without explanation or improvement.',proof:'Successive work versions, explanations and a reviewed improvement.'}],
};
export function practiceRanking(scores:Scores){if(!scores.complete)return {weakest:[] as Attribute[],targets:[] as Attribute[],weekend:'' as Attribute|''};const order=(c:Attribute)=>attributes.findIndex(a=>a[0]===c);const weakest=[...scores.factors].sort((a,b)=>a.blended!-b.blended!||order(a.code)-order(b.code)).slice(0,8);const targets=[...weakest].sort((a,b)=>a.code[1].localeCompare(b.code[1])||a.blended!-b.blended!||order(a.code)-order(b.code)).slice(0,3);return {weakest:weakest.map(f=>f.code),targets:targets.map(f=>f.code),weekend:[...targets].sort((a,b)=>a.blended!-b.blended!||order(a.code)-order(b.code))[0].code};}
export function makeReport(a:Assessment,source:'Self-rated'|'Mentor-rated',context:Context,review:MentorReview|null=null,id=crypto.randomUUID(),now=new Date().toISOString()):Report{
 const ratings=source==='Mentor-rated'&&review?review.ratings:a.answers.ratings,outcome=a.outcomes.at(-1)??null,scores=calculate(a.model,ratings,outcome);
 const scored=scores.factors.filter(f=>f.blended!==null),blocked=scores.gateRequirements.concat(scores.certRequirements).filter(r=>r.met===false&&r.code);
 const ordered=[...scored].sort((a,b)=>{const ab=blocked.some(r=>r.code===a.code)?1:0,bb=blocked.some(r=>r.code===b.code)?1:0;return bb-ab||(a.level!-b.level!)*.6-(a.gap!-b.gap!)*4;});
 const item=(f:FactorResult):Priority=>{
  const requirements=blocked.filter(r=>r.code===f.code),part:Part=requirements.find(r=>r.part)?.part??(f.p1!<=f.p2!?1:2),g=guidance[f.code][part-1],delta=f.p2!-f.p1!;
  const interpretation=Math.abs(delta)>=1?delta>0?`Part 2 is ${delta.toFixed(1)} marks above Part 1. The Part 2 behaviour may be better supported. Verify the difference with examples.`:`Part 1 is ${(-delta).toFixed(1)} marks above Part 2. The Part 2 behaviour may need more support. Verify this with examples.`:'The two ratings are close. Check whether both are supported by repeated examples, rather than assuming the same rating means the same skill.';
  const sources=[`${source} assessment rating`];if(review?.factorComments[f.code]||review?.comment)sources.push('Mentor observation');if(context.work.some(w=>w.attribute===f.code))sources.push('Recorded game/work evidence');
  return {code:f.code,part,name:f.name,level:f.level!,gap:f.gap!,why:requirements.length?`Requirement to review: ${requirements.map(r=>r.label).join('; ')}.`:`Factor level ${round2(f.level!)}%; ${round2(f.gap!)} of ${f.weight} weighted points remain. This is a relative development priority, not a diagnosis.`,interpretation,...g,source:sources,references:context.curriculum.filter(c=>c.code===f.code&&c.part===part)};
 };
 const priorities=ordered.slice(0,4).map(item),strengths=[...scored].filter(f=>f.level!>=80&&!priorities.some(p=>p.code===f.code)).sort((a,b)=>b.level!-a.level!).slice(0,3).map(item),supporting=ordered.filter(f=>!priorities.some(p=>p.code===f.code)&&!strengths.some(p=>p.code===f.code)).slice(0,2).map(item);
 const strongest=[...scored].sort((a,b)=>b.level!-a.level!).slice(0,2),summary=!scores.complete?'There is not enough rating evidence for a final score or gate decision.':`Your highest rated areas are ${strongest.map(f=>f.code+' '+f.name.toLowerCase()).join(' and ')}. Next, verify ${priorities.slice(0,2).map(p=>p.code+' Part '+p.part).join(' and ')} with your mentor. Ratings describe a development pattern; they do not establish personality, earning potential or complete mastery.`;
 return {id,assessmentId:a.id,rider:a.rider,riderName:a.riderName,source,reviewer:review?.mentorName??'',reviewDate:review?.date??null,generatedAt:now,model:structuredClone(a.model),answers:structuredClone(a.answers),selfRatings:structuredClone(a.answers.ratings),mentorRatings:review?structuredClone(review.ratings):null,outcome:outcome?structuredClone(outcome):null,scores,summary,priorities,supporting,strengths,context:structuredClone(context),weekend:practiceRanking(scores),mentorComments:review?.comment??'',reviewCycle:[{week:'Week 1',action:'Agree up to three priorities and any support needs with your mentor.'},{week:'Weeks 2–5',action:'Complete assigned curriculum activities. Keep brief examples of useful and difficult moments.'},{week:'Week 6',action:'Compare self-ratings, mentor observations and work evidence. Adjust the next steps.'},{week:'Weeks 7–8',action:'Reassess against the same rubric; compare the new assessment with this dated snapshot.'}]};
}
export const statusText=(r:Report)=>!r.scores.complete?'Incomplete — no final decision':r.outcome?.certified&&r.source==='Mentor-rated'&&r.scores.cert?'Certification confirmed by an authorised reviewer':r.source==='Self-rated'?(r.scores.gate?'Meets Ownership thresholds based on self-ratings — mentor confirmation pending.':'Ownership-entry development needed — based on self-ratings.'):(r.scores.cert?'Certification thresholds met — authorised decision pending.':r.outcome?.project==='Passed'&&r.scores.factors.find(f=>f.code==='C1B')!.level!<r.model.cert.c1bLevel?'C1B mentoring needed.':r.scores.gate?'Ownership entry confirmed; check remaining certification requirements.':'Ownership-entry requirements are not yet met.');
