import { database,RequestError } from './crew-server';
import { initialModel,canAccess,canReview,riderPlayer,type Assessment,type AssessmentRecord,type Model,type Context,type CurriculumRef } from './c310-model';
import { type Identity } from './jaguar';
import { type GrowthState } from './growth';
export async function models(){await database().prepare('INSERT OR IGNORE INTO c310_models(id,data,created_at) VALUES(?,?,?)').bind(initialModel.id,JSON.stringify(initialModel),initialModel.createdAt).run();const result=await database().prepare('SELECT data FROM c310_models ORDER BY created_at DESC,id DESC LIMIT 100').all<{data:string}>();return result.results.map(r=>JSON.parse(r.data) as Model);}
export async function assessment(id:string,u:Identity):Promise<AssessmentRecord>{const row=await database().prepare('SELECT data,revision,updated_at FROM c310_assessments WHERE id=?').bind(id).first<{data:string;revision:number;updated_at:string}>();if(!row)throw new RequestError('Assessment not found.',404);const a=JSON.parse(row.data) as Assessment;if(!canAccess(u,a))throw new RequestError('You cannot open another rider’s assessment.',403);return {assessment:a,revision:row.revision,updatedAt:row.updated_at};}
export async function assessmentList(u:Identity){const emails=[...new Set([u.email,...(await import('./jaguar')).crew.filter(c=>canReview(u,c.email)).map(c=>c.email)])];const result=await database().prepare(`SELECT data,revision,updated_at FROM c310_assessments WHERE rider IN (${emails.map(()=>'?').join(',')}) ORDER BY created_at DESC LIMIT 200`).bind(...emails).all<{data:string;revision:number;updated_at:string}>();return result.results.map(r=>({assessment:JSON.parse(r.data) as Assessment,revision:r.revision,updatedAt:r.updated_at}));}
export async function store(a:Assessment,revision:number){const now=new Date().toISOString(),result=await database().prepare('UPDATE c310_assessments SET data=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(a),now,a.id,revision).run();if(result.meta.changes!==1)throw new RequestError('This assessment changed. Reload saved data, then save your kept draft again.',409);return {assessment:a,revision:revision+1,updatedAt:now};}
export async function context(a:Assessment):Promise<Context>{
 const row=await database().prepare('SELECT data FROM growth_workspace WHERE id=?').bind('jaguar').first<{data:string}>(),growth=row?JSON.parse(row.data) as GrowthState:null,p=riderPlayer(a.rider);
 const latest=new Map<string,CurriculumRef>();for(const c of a.curriculum)latest.set(`${c.code}_${c.part}`,c);
 if(growth)for(const f of a.model.factors){const url=growth.settings.exerciseLinks[f.code];if(url)for(const part of [1,2] as const)if(!latest.has(`${f.code}_${part}`))latest.set(`${f.code}_${part}`,{id:`growth_${f.code}_${part}`,code:f.code,part,title:`C310 curriculum · ${f.code}`,url,note:'Existing factor-level mapping. Confirm the activity’s Part 1 / Part 2 relevance with your mentor.',by:'Existing curriculum mapping',assignedAt:''});}
 const work=p&&growth?growth.incidents.filter(i=>i.status==='Reviewed'&&i.affected.includes(p)).flatMap(i=>[i.attribute,...i.supporting].filter(Boolean).map(attribute=>({id:`${i.id}_${attribute}`,date:i.date,attribute,observation:i.observation,evidence:i.evidence,recovery:i.recovery}))).concat(growth.days.flatMap(d=>d.rows.filter(r=>r.player===p&&r.result).map(r=>({id:`${d.date}_${p}`,date:d.date,attribute:'',observation:r.task,evidence:r.result,recovery:''})))):[];
 const weekly=p&&growth?growth.practices.filter(w=>w.player===p).map(w=>({week:w.week,targets:w.targets,weekend:w.weekend,status:w.status,exerciseUrl:w.exerciseUrl,basis:w.c310?.source??'Existing leader tracker grades'})):[];
 return {riverStart:growth?.settings.start??'2026-10-03',riverWeeks:growth?(await import('./growth')).weekCount(growth.settings.start):14,work:work.sort((x,y)=>x.date.localeCompare(y.date)||x.id.localeCompare(y.id)).slice(-80),weekly,curriculum:[...latest.values()]};
}
export const c310Failure=(e:unknown)=>{if(e instanceof RequestError)return Response.json({error:e.message},{status:e.status,headers:{'Cache-Control':'private, no-store'}});console.error('C310 request failed',e instanceof Error?e.name:'unknown');return Response.json({error:'C310 could not load or save. Your open draft has been kept. Try again shortly.'},{status:503,headers:{'Cache-Control':'private, no-store'}});};
