import { createRequire } from 'node:module';
import { readFileSync,readdirSync } from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import vm from 'node:vm';
const require=createRequire(import.meta.url),wranglerRequire=createRequire(require.resolve('wrangler/package.json'));
const {Miniflare,Log,LogLevel}=wranglerRequire('miniflare');
const ts=require('typescript');
const js=ts.transpileModule(readFileSync('lib/jaguar.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const sandbox={exports:{},Date};vm.runInNewContext(js,sandbox);const {visibleRecords,energyState,appealDeadline,crew}=sandbox.exports;
const owner=crew[0],leader=crew[1],rider=crew[4],second=crew[2];
const scenario={id:'private',kind:'scenario',author:owner.email,data:{title:'Unreleased client change',releaseAt:'2026-10-22T04:30:00Z',published:true},createdAt:'2026-10-01T00:00:00Z'};
assert.equal(visibleRecords([scenario],owner,new Date('2026-10-01')).length,1);
assert.equal(visibleRecords([scenario],leader,new Date('2026-10-19T18:29:59Z')).length,0);
assert.equal(visibleRecords([scenario],leader,new Date('2026-10-19T18:30:00Z')).length,1);
assert.equal(visibleRecords([scenario],rider,new Date('2026-10-22T04:29:59Z')).length,0);
assert.equal(visibleRecords([scenario],rider,new Date('2026-10-22T04:30:00Z')).length,1);
assert.equal(visibleRecords([{...scenario,data:{...scenario.data,published:false}}],rider,new Date('2026-12-01')).length,0);
let losses=[];for(let i=0;i<8;i++)losses.push({kind:'energy',data:{rider:rider.email},createdAt:`2026-10-${String(i+1).padStart(2,'0')}`});
assert.equal(energyState(losses,rider.email).reviewRequired,true);
losses[0].data.appealStatus='upheld';assert.equal(energyState(losses,rider.email).energy,1);
assert.equal(appealDeadline(new Date('2026-10-02T11:30:00Z')),'2026-10-05T05:30:00.000Z');
console.log('Passed: scenario release boundaries, private drafts, appeal restoration and working-hour deadline.');
let providerPayload;
const walk=dir=>readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):e.name.endsWith('.js')?[path.join(dir,e.name)]:[]);
const modulePaths=walk(path.resolve('dist/server'));const entry=path.resolve('dist/server/index.js');modulePaths.splice(modulePaths.indexOf(entry),1);modulePaths.unshift(entry);
const mf=new Miniflare({modules:modulePaths.map(p=>({type:'ESModule',path:p})),modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test-jaguar'},r2Buckets:{BUCKET:'test-files'},bindings:{OPENAI_API_KEY:'test-placeholder-not-a-real-key',OPENAI_MODEL:'gpt-5-mini'},log:new Log(LogLevel.ERROR),outboundService:async request=>{if(new URL(request.url).hostname==='api.openai.com'){providerPayload=await request.json();return new Response(JSON.stringify({output:[{content:[{type:'output_text',text:'Check your synthetic HDL mapping against the acceptance criteria, then reconcile loaded workers.'}]}],usage:{input_tokens:100,output_tokens:20}}),{headers:{'Content-Type':'application/json'}});}return fetch(request);}});
try{
 const db=await mf.getD1Database('DB');
 for(const statement of readFileSync('drizzle/0000_cuddly_ma_gnuci.sql','utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(statement).run();
 const request=async(email,body,url='/api/crew')=>{const headers=email?{'oai-authenticated-user-id':'test-'+email,'oai-authenticated-user-email':email}:{};if(body)headers['Content-Type']='application/json';const response=await mf.dispatchFetch('http://jaguar.test'+url,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});let data;try{data=await response.json();}catch{throw new Error(`Non-JSON response from ${url}: ${response.status}`)}return {status:response.status,data};};
 const ok=async(email,body,url)=>{const r=await request(email,body,url);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};
 assert.equal((await request(null)).status,401);assert.equal((await request('rishidharshini@cloudheard.org')).status,403);
 assert.equal((await request(rider.email,{op:'task',title:'Unauthorized'})).status,403);
 const initial=await ok(owner.email);assert.equal(initial.records.filter(r=>['post','task','evidence','raid'].includes(r.kind)).length,0);
 const task=(await ok(owner.email,{op:'task',title:'Synthetic HDL mapping',description:'Map three masked worker rows for India.',owner:rider.email,dueAt:'2026-10-09T12:00:00Z',criteria:'Three workers mapped; totals reconciled.',dependency:'',jira:''})).id;
 const task2=(await ok(owner.email,{op:'task',title:'Dependent test',description:'Verify approved mapping.',owner:second.email,dueAt:'2026-10-12T12:00:00Z',criteria:'Mapping accepted first.',dependency:task,jira:''})).id;
 let all=(await ok(rider.email)).records;let t=all.find(r=>r.id===task),dep=all.find(r=>r.id===task2);
 assert.equal((await request(second.email,{op:'task_status',id:task,revision:t.revision,status:'In progress'})).status,403);
 assert.equal((await request(second.email,{op:'task_status',id:task2,revision:dep.revision,status:'In progress'})).status,400);
 await ok(rider.email,{op:'readiness',confirmed:true});
 const post=(await ok(rider.email,{op:'post',text:'Masked source workbook is ready for peer review.'})).id;
 await ok(second.email,{op:'reply',parentId:post,text:'I will check the legal employer codes.'});
 assert.equal((await request(second.email,{op:'config',jira:'',aiEnabled:false})).status,403);
 await ok(leader.email,{op:'admin',weeklyAdmin:rider.email});
 const fd=new FormData();fd.append('file',new File(['SYNTHETIC WORKER,LEGAL_EMPLOYER\nW001,TMS_INDIA'],'mapping.csv',{type:'text/csv'}));
 const encodedFile=new Request('http://jaguar.test/api/files',{method:'POST',body:fd});
 let fileResponse=await mf.dispatchFetch('http://jaguar.test/api/files',{method:'POST',headers:{...Object.fromEntries(encodedFile.headers),'oai-authenticated-user-id':'test-rider','oai-authenticated-user-email':rider.email},body:await encodedFile.arrayBuffer()});assert.equal(fileResponse.status,200);const upload=await fileResponse.json();
 const e1=(await ok(rider.email,{op:'evidence',taskId:task,title:'Cycle 1 reconciliation',summary:'Three synthetic workers checked.',handoff:'Premothan to review mapping.',attachmentId:upload.id,link:''})).id;
 all=(await ok(leader.email)).records;let evidence=all.find(r=>r.id===e1);
 assert.equal((await request(rider.email,{op:'review',id:e1,revision:evidence.revision,decision:'Accepted',feedback:'Self-approved'})).status,403);
 await ok(leader.email,{op:'review',id:e1,revision:evidence.revision,decision:'Rework',feedback:'Explain the missing source row.',validation:'Expected 3 mapped workers; actual evidence shows 2.',c1:3,c2:2,c3:3});
 const e2=(await ok(rider.email,{op:'evidence',taskId:task,title:'Cycle 1 reconciliation',summary:'All three synthetic workers reconciled.',handoff:'Premothan to accept mapping.',attachmentId:upload.id,link:'',groupId:evidence.data.groupId})).id;
 all=(await ok(leader.email)).records;evidence=all.find(r=>r.id===e2);assert.equal(evidence.data.version,2);
 await ok(leader.email,{op:'review',id:e2,revision:evidence.revision,decision:'Accepted',feedback:'Reconciliation and hand-off verified.',validation:'Expected 3; actual 3; file opens.',c1:4,c2:4,c3:4});
 all=(await ok(second.email)).records;assert.equal(all.find(r=>r.id===task).data.status,'Accepted');assert.equal(all.filter(r=>r.kind==='evidence').length,2);assert.equal(all.filter(r=>r.kind==='reply').length,1);
 const dl=await mf.dispatchFetch('http://jaguar.test/api/files/'+upload.id,{headers:{'oai-authenticated-user-id':'test-second','oai-authenticated-user-email':second.email}});assert.equal(dl.status,200);assert.match(await dl.text(),/SYNTHETIC WORKER/);
 await ok(rider.email,{op:'raid',type:'Issue / Blocker',title:'Missing source value',detail:'One source row needs clarification; owner informed.',owner:rider.email,eta:'2026-10-07T12:00:00Z',jira:'',evidence:''});
 const loss=(await ok(leader.email,{op:'energy',rider:rider.email,rule:'EVIDENCE',detail:'Verified training breach with timestamp and evidence.',evidence:'https://example.org/synthetic-breach-proof'})).id;
 let ledger=(await ok(rider.email)).records.find(r=>r.id===loss);assert.equal(ledger.data.before.energy,2);assert.equal(ledger.data.after.energy,1);
 assert.equal((await request(second.email,{op:'appeal',id:loss,revision:ledger.revision,reason:'Wrong rider attempting appeal.'})).status,403);
 await ok(rider.email,{op:'appeal',id:loss,revision:ledger.revision,reason:'The evidence was submitted before deadline.'});
 ledger=(await ok(leader.email)).records.find(r=>r.id===loss);
 await ok(leader.email,{op:'appeal_review',id:loss,revision:ledger.revision,decision:'upheld',feedback:'Timestamp verified; restore the energy.'});
 assert.equal(energyState((await ok(rider.email)).records,rider.email).energy,2);
 await ok(owner.email,{op:'scenario',type:'Client Change Request',title:'PRIVATE SCENARIO MARKER',detail:'Future training event withheld until release.',releaseAt:'2026-11-20T04:30:00Z',published:true});
 const riderRecords=(await ok(rider.email)).records;assert.equal(riderRecords.some(r=>r.kind==='scenario'),false);
 await ok(rider.email,{question:'What should I check before loading the HDL mapping?',taskId:task},'/api/guide');
 assert.match(providerPayload.instructions,/TMS Motors/);assert.match(providerPayload.instructions,/Abinesh S/);assert.match(providerPayload.instructions,/Synthetic HDL mapping/);assert.doesNotMatch(providerPayload.instructions,/PRIVATE SCENARIO MARKER/);assert.equal(providerPayload.store,false);
 await ok(owner.email,{op:'config',jira:'https://example.atlassian.net/jira/software/projects/JAG',aiEnabled:false});assert.equal((await request(rider.email,{question:'Explain legal employers.'},'/api/guide')).status,503);
 assert.equal((await ok(owner.email)).records.find(r=>r.kind==='config').data.weeklyAdmin,rider.email);
 console.log('Passed: anonymous/removed-member access; role enforcement; shared posts/replies; task dependencies; R2 upload/download; evidence versions, rework and acceptance; RAID; private scenarios; automatic AI context and kill switch.');
 console.log('All Jaguar checks passed. Test data stayed in an isolated local database.');
}finally{await mf.dispose();}
