import {createRequire} from 'node:module';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import assert from 'node:assert/strict';
import {PDFDocument} from 'pdf-lib';
const require=createRequire(import.meta.url),ts=require('typescript');
function load(file,imports={},sourceOverride=null){const exports={};const source=ts.transpileModule(sourceOverride??fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;new Function('require','exports',source)(n=>imports[n]??require(n),exports);return exports;}
const jaguar=load('lib/jaguar.ts'),growth=load('lib/growth.ts'),model=load('lib/c310-model.ts',{'./jaguar':jaguar,'./growth':growth}),pdf=load('lib/c310-pdf.ts',{'./c310-model':model,'./c310-fonts':load('lib/c310-fonts.ts'),'@pdf-lib/fontkit':{default:require('@pdf-lib/fontkit')}});
const fixture=[[2,5],[2,5],[3,5],[4.5,5],[5,5],[2,5],[2,4],[5,5],[2,5],[5,5]];
const ratings=model.emptyRatings();ratings.forEach((r,i)=>{r.p1=fixture[i][0];r.p2=fixture[i][1];});
const outcome={id:'fixture-outcome',project:'Passed',evidence:'Named regression fixture only; not a live project outcome',certified:false,by:'Regression fixture',date:'2026-10-06T00:00:00Z'};
let s=model.calculate(model.initialModel,ratings,outcome);assert.equal(s.scoreB,80.22);assert.equal(s.scoreA,82.02);assert.equal(s.factors.find(f=>f.code==='C1B').level,64);assert.equal(s.gate,true);assert.equal(s.cert,false);
const c1b=structuredClone(ratings);c1b[1].p1=4;c1b[1].p2=4;s=model.calculate(model.initialModel,c1b,outcome);assert.equal(s.scoreB,81.82);assert.equal(s.factors[1].level,80);assert.equal(s.cert,true);
const aspiration=structuredClone(ratings);for(const code of ['C1B','C2B','C2C','C3A'])aspiration.find(r=>r.code===code).p1=4;aspiration.find(r=>r.code==='C2C').p2=4.5;assert.equal(model.calculate(model.initialModel,aspiration,outcome).scoreB,90.38);assert.equal(ratings[1].p1,2);
const missing=structuredClone(ratings);missing[0].p1=null;s=model.calculate(model.initialModel,missing);assert.equal(s.complete,false);assert.equal(s.scoreA,null);assert.equal(s.scoreB,null);assert.equal(s.gate,null);assert.equal(s.cert,null);
const zero=structuredClone(ratings);zero[0].p1=0;s=model.calculate(model.initialModel,zero);assert.equal(s.complete,true);assert.equal(s.gate,false);
for(const [code,part,min] of [['C1A',1,2],['C1C',1,2],['C1C',2,1.5],['C2B',2,2.5]]){const r=structuredClone(ratings);r.find(r=>r.code===code)[part===1?'p1':'p2']=min-.5;assert.equal(model.calculate(model.initialModel,r).gate,false);}
// Aggregate score rounding, not an unrounded intermediate, owns the threshold check.
const rounded=structuredClone(model.initialModel);rounded.gate.scoreA=82.02;assert.equal(model.calculate(rounded,ratings).gate,true);
const a={id:'lavy-regression-only',rider:'fixture@example.invalid',riderName:'Lavy / regression example',model:structuredClone(model.initialModel),answers:{subject:'Oracle Fusion HCM',path:'Working-model regression fixture',date:'2026-10-06',ratings:structuredClone(ratings),barriers:'No structural barriers supplied in this named test fixture.',support:'Discuss accommodations and feasible practice with the mentor.',reflection:''},status:'Reviewed',mentorReviews:[],curriculum:[],outcomes:[outcome],reports:[],createdAt:'2026-10-06T00:00:00Z',previousId:null};
const ctx={work:[],weekly:[],curriculum:[]},report=model.makeReport(a,'Self-rated',ctx,null,'fixture-report','2026-10-06T00:00:00Z');assert.match(model.statusText(report),/mentor confirmation pending/);assert.ok(report.priorities.some(p=>p.code==='C1B'));assert.ok(report.priorities.some(p=>p.code==='C2B'));assert.equal(report.priorities.every(p=>p.references.length===0),true);
const high=structuredClone(a);high.answers.ratings.forEach(r=>{r.p1=5;r.p2=5;});const highReport=model.makeReport(high,'Self-rated',ctx);assert.equal(highReport.scores.scoreB,100);assert.match(highReport.summary,/do not establish.*complete mastery/);
const weakSubject=structuredClone(a);weakSubject.answers.ratings.forEach(r=>{r.p1=4;r.p2=4;});weakSubject.answers.ratings.find(r=>r.code==='C2A').p2=0;const subjectReport=model.makeReport(weakSubject,'Self-rated',ctx);assert.ok(subjectReport.priorities.some(p=>p.code==='C2A'&&p.part===2));assert.notEqual(JSON.stringify(subjectReport.priorities),JSON.stringify(report.priorities));
const tmp='/workspace/scratch/dd0f94d3317e/tmp/c310-pdfs';fs.mkdirSync(tmp,{recursive:true});
for(const [name,r,hypo] of [['lavy-regression',report,null],['lavy-hypothetical',report,aspiration],['missing',model.makeReport({...a,answers:{...a.answers,ratings:missing}},'Self-rated',ctx),null],['all-zero',model.makeReport({...a,answers:{...a.answers,ratings:model.emptyRatings().map(r=>({...r,p1:0,p2:0}))}},'Self-rated',ctx),null],['all-five',highReport,null],['subject-priority',subjectReport,null]]){
 const bytes=await pdf.buildReportPdf(r,hypo),document=await PDFDocument.load(bytes);assert.equal(document.getPageCount(),4,name+' has exactly four A4 pages');for(const page of document.getPages()){assert.ok(Math.abs(page.getWidth()-595.28)<.01);assert.ok(Math.abs(page.getHeight()-841.89)<.01);}fs.writeFileSync(path.join(tmp,name+'.pdf'),bytes);
}
const dense=structuredClone(report);dense.answers.barriers='A detailed structural barrier example. '.repeat(70);dense.answers.support='An agreed accommodation and support example. '.repeat(60);dense.mentorComments='A specific mentor observation with examples. '.repeat(60);dense.context.weekly=[1,2].map(week=>({week,targets:['C1A','C1B','C1C'],weekend:'C1A',status:'Needs retry',exerciseUrl:'',basis:'Existing tracker priorities'}));dense.answers.subject='A long but valid chosen subject name with additional context '.repeat(3).slice(0,160);dense.answers.path='A long but valid chosen route with practical context '.repeat(4).slice(0,160);dense.context.work=[1,2,3].map(n=>({id:'work-'+n,date:'2026-10-06',attribute:'C2B',observation:'A reviewed task and problem-solving observation. '.repeat(20),evidence:'Specific reviewed work evidence with the observed outcome. '.repeat(20),recovery:'Output recovered with an improved method'}));for(const priority of [...dense.priorities,...dense.supporting,...dense.strengths])priority.references=[{id:'qa-'+priority.code,code:priority.code,part:priority.part,title:'A real curriculum resource title supplied only for the test',url:'https://example.org/curriculum/actual-resource',note:'Test reference; never a live seeded activity',by:'QA',assignedAt:'2026-10-06'}];
const denseBytes=await pdf.buildReportPdf(dense,aspiration);assert.equal((await PDFDocument.load(denseBytes)).getPageCount(),4);fs.writeFileSync(path.join(tmp,'dense-hypothetical.pdf'),denseBytes);
const maxScenario=ratings.map(r=>({...r,p1:.5,p2:.5}));assert.equal((await PDFDocument.load(await pdf.buildReportPdf(dense,maxScenario))).getPageCount(),4);
console.log('Passed: three workbook examples, aggregate rounding, all mandatory minimums, missing versus zero, subject-specific narratives and four-page PDF cases including long evidence.');
if(process.argv.includes('--pdf-only'))process.exit(0);
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
const uiSource=fs.readFileSync('app/c310-report.tsx','utf8')+'\nexport const qaComponents={AssessmentForm,ReportView,MentorForm,CurriculumForm,OutcomeForm,WeekendForm,ModelEditor,HistoryChart};';
const uiImports={'../lib/c310-model':model,'../lib/jaguar':{...jaguar,istDate:()=> '2026-10-06'},'../lib/growth':growth,'./c310.css':{},'../components/ui/progress':{Progress:props=>React.createElement('progress',{value:props.value,max:100,'aria-label':props['aria-label']})},'../components/ui/chart':{ChartContainer:({children})=>React.createElement('div',{},children)}};
const recFixture={assessment:a,revision:1,updatedAt:a.createdAt},send=async()=>null;
for(let page=1;page<=4;page++){const ui=load('app/c310-report.tsx',uiImports,uiSource.replace('[page,setPage]=useState(1)',`[page,setPage]=useState(${page})`));const markup=renderToStaticMarkup(React.createElement(ui.qaComponents.ReportView,{report,liveReview:null}));assert.ok(markup.length>1500);assert.doesNotMatch(markup,/NaN|undefined/);assert.match(markup,/Download four-page PDF/);if(page===1){assert.match(markup,/80.22/);assert.match(markup,/82.02/);assert.match(markup,/available weighted points/);}if(page===2)assert.match(markup,/C2B/);if(page===3)assert.match(markup,/Curriculum activity to be assigned by your mentor/);if(page===4){assert.match(markup,/Mentor P1 \/ P2 at snapshot/);assert.match(markup,/What would improvement look like/);}}
for(let stage=0;stage<=3;stage++){const ui=load('app/c310-report.tsx',uiImports,uiSource.replace('[stage,setStage]=useState(0)',`[stage,setStage]=useState(${stage})`));const markup=renderToStaticMarkup(React.createElement(ui.qaComponents.AssessmentForm,{record:recFixture,send,busy:false}));assert.match(markup,/Save draft/);assert.doesNotMatch(markup,/NaN|undefined/);if(stage===3)assert.match(markup,/Save &amp; generate report/);else{assert.match(markup,/Not enough evidence yet/);assert.match(markup,/value="4.5"/);}}
const ui=load('app/c310-report.tsx',uiImports,uiSource);
for(const [name,props] of [['MentorForm',{record:recFixture,user:{email:'mechpremothan@gmail.com',name:'Premothan',role:'cohort_leader'},send,busy:false}],['CurriculumForm',{record:recFixture,send,busy:false}],['OutcomeForm',{record:recFixture,send,busy:false}],['WeekendForm',{record:recFixture,send,busy:false,ctx}],['ModelEditor',{model:model.initialModel,publish:()=>{},busy:false}]]){const markup=renderToStaticMarkup(React.createElement(ui.qaComponents[name],props));assert.ok(markup.length>500,name);assert.doesNotMatch(markup,/NaN|undefined/,name);if(name==='MentorForm')assert.match(markup,/Draft · incomplete/);}
console.log('Passed: all four web report pages, all four assessment stages, independently blank mentor inputs, curriculum/outcome/weekend forms and versioned model editor.');

const wranglerRequire=createRequire(require.resolve('wrangler/package.json')),{Miniflare,Log,LogLevel}=wranglerRequire('miniflare');
const walk=dir=>fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(dir,e.name)):e.name.endsWith('.js')?[path.join(dir,e.name)]:[]),files=walk(path.resolve('dist/server')),entry=path.resolve('dist/server/index.js');files.splice(files.indexOf(entry),1);files.unshift(entry);
const mf=new Miniflare({modules:files.map(p=>({type:'ESModule',path:p})),modulesRoot:path.resolve('dist/server'),compatibilityDate:'2026-05-15',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'qa-c310'},r2Buckets:{BUCKET:'qa-c310-files'},log:new Log(LogLevel.ERROR)});
try{
 const db=await mf.getD1Database('DB');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())for(const stmt of fs.readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint').map(s=>s.trim()).filter(Boolean))await db.prepare(stmt).run();
 const owner='lavanyabalaji123@gmail.com',lead='mechpremothan@gmail.com',rider='sasiabinesh292@gmail.com',other='stephan@cloudheard.org';
 const request=async(email,body,url='/api/c310',origin)=>{const headers=email?{'oai-authenticated-user-id':'qa-'+email,'oai-authenticated-user-email':email}:{};if(body)headers['Content-Type']='application/json';if(origin)headers.Origin=origin;const r=await mf.dispatchFetch('http://jaguar.test'+url,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});const data=r.headers.get('content-type')?.startsWith('application/pdf')?new Uint8Array(await r.arrayBuffer()):await r.json();return {status:r.status,data,headers:r.headers};};
 const ok=async(email,body,url)=>{const r=await request(email,body,url);assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};
 assert.equal((await request(null)).status,401);assert.equal((await request('rishidharshini@cloudheard.org')).status,403);
 const initial=await ok(rider);assert.equal(initial.assessments.length,0);assert.equal(initial.models[0].factors[1].provisional,true);
 let rec=(await ok(rider,{op:'new',previousId:null})).record;assert.ok(rec.assessment.answers.ratings.every(r=>r.p1===null&&r.p2===null));const id=rec.assessment.id;
 const op=async(who,operation,extra={})=>{const result=await ok(who,{op:operation,id,revision:rec.revision,...extra});rec=result.record;return result;};
 assert.equal((await request(other,{op:'draft',id,revision:1,answers:a.answers})).status,403);assert.equal((await request(rider,{op:'submit',id,revision:1})).status,400);
 await op(rider,'draft',{answers:{...a.answers,ratings:missing}});assert.equal((await request(rider,{op:'submit',id,revision:rec.revision})).status,400);
 await op(rider,'draft',{answers:{...a.answers,ratings:ratings}});const stale=rec.revision;await op(rider,'submit');assert.equal(rec.assessment.reports[0].scores.scoreB,80.22);assert.equal(rec.assessment.reports[0].scores.scoreA,82.02);
 assert.equal((await request(rider,{op:'draft',id,revision:rec.revision,answers:a.answers})).status,400);assert.equal((await request(rider,{op:'request',id,revision:stale})).status,409);
 assert.equal((await request(rider,{op:'outcome',id,revision:rec.revision,project:'Passed',evidence:'Self-approved',certified:true})).status,403);
 await op(rider,'request');assert.equal(rec.assessment.status,'Review requested');
 const foreign=await ok(other);assert.equal(foreign.assessments.some(r=>r.assessment.id===id),false);assert.equal((await ok(lead)).assessments.some(r=>r.assessment.id===id),true);
 const independent=structuredClone(ratings);independent[1].p1=1;
 await op(lead,'mentor_draft',{reviewId:null,ratings:independent,date:'2026-10-06',comment:'Observed independent work and explanations.',factorComments:{C1B:'Needs supported institutional participation.'}});let reviewId=rec.assessment.mentorReviews.at(-1).id;
 await op(lead,'mentor_confirm',{reviewId});assert.equal(rec.assessment.answers.ratings[1].p1,2);assert.equal(rec.assessment.mentorReviews[0].ratings[1].p1,1);assert.equal(rec.assessment.reports.at(-1).source,'Mentor-rated');
 await op(lead,'assign',{code:'C1B',part:1,title:'Actual curriculum resource supplied in test',url:'https://example.org/real-training-resource',note:'This test URL is not seeded into the live product.'});assert.equal(rec.assessment.reports.at(-1).context.curriculum[0].url,'https://example.org/real-training-resource');
 const frozenSelf=JSON.stringify(rec.assessment.reports[0]);
 await op(owner,'outcome',{project:'Passed',evidence:'Reviewed independent training project and acceptance evidence.',certified:false});assert.equal(rec.assessment.outcomes.at(-1).project,'Passed');assert.equal(rec.assessment.reports.at(-1).scores.cert,false);
 assert.equal((await request(owner,{op:'outcome',id,revision:rec.revision,project:'Passed',evidence:'Project passed',certified:true})).status,400);
 await op(lead,'mentor_draft',{reviewId:null,ratings:c1b,date:'2026-10-06',comment:'New observed evidence supports ratings 4 and 4 for C1B.',factorComments:{C1B:'Supported participation demonstrated.'}});reviewId=rec.assessment.mentorReviews.at(-1).id;await op(lead,'mentor_confirm',{reviewId});assert.equal(rec.assessment.reports.at(-1).scores.scoreB,81.82);
 await op(owner,'outcome',{project:'Passed',evidence:'Reviewed project evidence and all threshold requirements.',certified:true});assert.equal(rec.assessment.reports.at(-1).outcome.certified,true);assert.equal(JSON.stringify(rec.assessment.reports[0]),frozenSelf);
 const pdfPath=`/api/c310/${id}/pdf?report=${rec.assessment.reports.at(-1).id}`;assert.equal((await request(other,undefined,pdfPath)).status,403);const exported=await request(rider,undefined,pdfPath);assert.equal(exported.status,200);assert.match(exported.headers.get('content-disposition'),/attachment/);assert.equal((await PDFDocument.load(exported.data)).getPageCount(),4);
 const pdfHypo=await request(rider,undefined,pdfPath+'&scenario='+encodeURIComponent(JSON.stringify(aspiration.map(({code,p1,p2})=>({code,p1,p2})))));assert.equal(pdfHypo.status,200);assert.equal((await PDFDocument.load(pdfHypo.data)).getPageCount(),4);
 await op(lead,'weekend',{week:1});const grow=await ok(lead,undefined,'/api/growth');const plan=grow.state.practices[0];assert.equal(plan.player,'Abinesh');assert.equal(JSON.stringify(plan.targets),JSON.stringify(model.practiceRanking(model.calculate(model.initialModel,c1b,outcome)).targets));assert.equal(plan.c310.source,'Mentor-assessment blended grades');assert.equal((await request(rider,undefined,'/api/growth')).status,403);
 assert.equal((await request(lead,{op:'model',data:{version:'QA v2',factors:model.initialModel.factors,gate:model.initialModel.gate,cert:model.initialModel.cert,note:'Test version'}})).status,403);
 await ok(owner,{op:'model',data:{version:'QA v2',factors:model.initialModel.factors,gate:{...model.initialModel.gate,scoreA:90},cert:model.initialModel.cert,note:'Test version, historical assessment retained'}});const back=(await ok(rider)).assessments.find(r=>r.assessment.id===id);assert.equal(back.assessment.model.id,model.initialModel.id);assert.equal(back.assessment.reports[0].scores.scoreB,80.22);
 const next=(await ok(rider,{op:'new',previousId:id})).record;assert.equal(next.assessment.previousId,id);assert.equal(next.assessment.model.version,'QA v2');assert.ok(next.assessment.answers.ratings.every(r=>r.p1===null));
 assert.equal((await request(rider,{op:'draft',id:next.assessment.id,revision:1,answers:{...a.answers,scoreB:100}})).status,400);assert.equal((await request(rider,{op:'new',previousId:null},'/api/c310','https://untrusted.example')).status,403);
 const leadOwn=(await ok(lead,{op:'new',previousId:null})).record;assert.equal((await request(lead,{op:'mentor_draft',id:leadOwn.assessment.id,revision:1,reviewId:null,ratings,date:'2026-10-06',comment:'Self-review',factorComments:{}})).status,403);
 console.log('Passed: saved drafts, immutable reports, independent mentor ratings, assigned curriculum, authorised project/certification outcomes, cross-rider blocks including PDFs, config version history, reassessment, weekend integration, forged-score rejection and four-page Worker PDF exports.');
}finally{await mf.dispose();}
